# Quantitative Momentum Strategy

"Momentum investing" means investing in the stocks that have increased in price the most.

For this project, we're going to build an investing strategy that selects the 50 stocks with the highest price momentum. From there, we will calculate recommended trades for an equal-weight portfolio of these 50 stocks.


## Library Imports

The first thing we need to do is import the open-source software libraries that we'll be using in this tutorial.

In [2]:
%pip install yfinance

Requirement already satisfied: yfinance in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (1.2.1)
Requirement already satisfied: pandas>=1.3.0 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from yfinance) (3.0.2)
Requirement already satisfied: numpy>=1.16.5 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from yfinance) (2.4.4)
Requirement already satisfied: requests>=2.31 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from yfinance) (2.33.1)
Requirement already satisfied: multitasking>=0.0.7 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from yfinance) (4.9.4)
Requirement already satisfied: pytz>=2022.5 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from yfinance) (2026.1.post1)
Requirement already satisfied: frozendict>=2.3.4 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from yfinance) (4.0.4)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from yfinance) (4.14.3)
Requirement already satisfied: curl_cffi>=0.15 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from yfinance) (7.34.1)
Requirement already satisfied: websockets>=13.0 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from yfinance) (16.0)
Requirement already satisfied: soupsieve>=1.6.1 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (2026.2.25)
Requirement already satisfied: rich in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (14.3.3)
Requirement already satisfied: pycparser in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.6.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from rich->curl_cffi>=0.15->yfinance) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from rich->curl_cffi>=0.15->yfinance) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /Users/favourstjohn/Desktop/Algorithmic Trading Using Python/.venv/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [18]:
import numpy as np
import pandas as pd
import requests
import math
from scipy.stats import percentileofscore as score
import xlsxwriter
import yfinance as yf

## Importing Our List of Stocks

As before, we'll need to import our list of stocks and our API token before proceeding. Make sure the `.csv` file is still in your working directory and import it with the following command:

In [4]:
stocks = pd.read_csv('sp_500_stocks.csv')

## Making Our First API Call

It's now time to make the first version of our momentum screener!

We need to get one-year price returns for each stock in the universe. Here's how.

In [5]:
symbol = 'AAPL'
ticker = yf.Ticker(symbol)
data = ticker.info
data

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers exclusive original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 150000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 64,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'totalPay': 16759518,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kevan  Parekh',
   'age': 53,
   'title': 'Senior VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4034174,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sabih  Khan',
   'age': 58,
   'title': 'Senior VP & Chief Operating Officer',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5021905,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 58,
   'title': 'Senior Vice President of Retail & People',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5037867,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 61,
   'title': 'Senior VP of Government Affairs & Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2025,
   'totalPay': 5022482,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ben  Borders',
   'age': 44,
   'title': 'Principal Accounting Officer',
   'yearBorn': 1981,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Jennifer G. Newstead J.D.',
   'age': 54,
   'title': 'Senior VP & General Counsel',
   'yearBorn': 1971,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kristin Huguet Quayle',
   'title': 'Vice President of Worldwide Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 2,
 'boardRisk': 1,
 'compensationRisk': 7,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1775001600,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://investor.apple.com/',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 258.79,
 'open': 258.095,
 'dayLow': 257.82,
 'dayHigh': 261.13,
 'regularMarketPreviousClose': 258.79,
 'regularMarketOpen': 258.095,
 'regularMarketDayLow': 257.82,
 'regularMarketDayHigh': 261.13,
 'dividendRate': 1.04,
 'dividendYield': 0.4,
 'exDividendDate': 1770595200,
 'payoutRatio': 0.1304,
 'fiveYearAvgDividendYield': 0.51,
 'beta': 1.109,
 'trailingPE': 33.03422,
 'forwardPE': 27.989,
 'volume': 8806477,
 'regularMarketVolume': 8806833,
 'averageVolume': 47195496,
 'averageVolume10days': 39732000,
 'averageDailyVolume10Day': 39732000,
 'bid': 260.19,
 'ask': 262.98,
 'bidSize': 2,
 'askSize': 4,
 'marketCap': 3830867558400,
 'nonDilutedMarketCap': 3799919466200,
 'fiftyTwoWeekLow': 189.81,
 'fiftyTwoWeekHigh': 288.62,
 'allTimeHigh': 288.62,
 'allTimeLow': 0.049107,
 'priceToSalesTrailing12Months': 8.794287,
 'fiftyDayAverage': 260.8828,
 'twoHundredDayAverage': 251.2118,
 'trailingAnnualDividendRate': 1.03,
 'trailingAnnualDividendYield': 0.003980061,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3823521497088,
 'profitMargins': 0.27037,
 'floatShares': 14655888439,
 'sharesOutstanding': 14681140000,
 'sharesShort': 129553812,
 'sharesShortPriorMonth': 133373267,
 'sharesShortPreviousMonthDate': 1770940800,
 'dateShortInterest': 1773360000,
 'heldPercentInsiders': 0.01641,
 'heldPercentInstitutions': 0.65312,
 'shortRatio': 3.17,
 'shortPercentOfFloat': 0.0085,
 'impliedSharesOutstanding': 14697926000,
 'bookValue': 5.998,
 'priceToBook': 43.454487,
 'lastFiscalYearEnd': 1758931200,
 'nextFiscalYearEnd': 1790467200,
 'mostRecentQuarter': 1766793600,
 'earningsQuarterlyGrowth': 0.159,
 'netIncomeToCommon': 117776998400,
 'trailingEps': 7.89,
 'forwardEps': 9.31223,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 8.777,
 'enterpriseToEbitda': 25.006,
 '52WeekChange': 0.33232105,
 'SandP52WeekChange': 0.3206551,
 'lastDividendValue': 0.26,
 'lastDividendDate': 1770595200,
 'quoteType': 'EQUITY',
 'currentPrice': 260.645,
 'targetHighPrice': 350.0,
 'targetLowPrice': 205.0,
 'targetMeanPrice': 296.3305,
 'targetMedianPrice': 300.0,
 'recommendationMean': 1.89583,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 40,
 'totalCash': 66907000832,
 'totalCashPerShare': 4.557,
 'ebitda': 152901992448,
 'totalDebt': 90509000704,
 'quickRatio': 0.845,
 'currentRatio': 0.974,
 'totalRevenue': 435617005568,
 'debtToEquity': 102.63,
 'revenuePerShare': 29.305,
 'returnOnAssets': 0.24377,
 'returnOnEquity': 1.5202099,
 'grossProfits': 206157004800,
 'freeCashflow': 106312753152,
 'operatingCashflow': 135471996928,
 'earningsGrowth': 0.183,
 'revenueGrowth': 0.157,
 'grossMargins': 0.47325,
 'ebitdaMargins': 0.35099998,
 'operatingMargins': 0.35374,
 'financialCurrency': 'USD',
 'symbol': 'AAPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'corporateActions': [],
 'regularMarketTime': 1776263684,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_24937',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'regularMarketChangePercent': 0.71486765,
 'regularMarketPrice': 260.64,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 345479400000,
 'regularMarketChange': 1.8500061,
 'regularMarketDayRange': '257.82 - 261.13',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 47195496,
 'fiftyTwoWeekLowChange': 70.83002,
 'fiftyTwoWeekLowChangePercent': 0.37316272,
 'fiftyTwoWeekRange': '189.81 - 288.62',
 'fiftyTwoWeekHighChange': -27.97998,
 'fiftyTwoWeekHighChangePercent': -0.09694401,
 'fiftyTwoWeekChangePercent': 33.232105,
 'dividendDate': 1770854400,
 'earningsTimestamp': 1777579200,
 'earningsTimestampStart': 1777579200,
 'earningsTimestampEnd': 1777579200,
 'earningsCallTimestampStart': 1777582800,
 'earningsCallTimestampEnd': 1777582800,
 'isEarningsDateEstimate': False,
 'epsTrailingTwelveMonths': 7.89,
 'epsForward': 9.31223,
 'epsCurrentYear': 8.52255,
 'priceEpsCurrentYear': 30.5824,
 'fiftyDayAverageChange': -0.24279785,
 'fiftyDayAverageChangePercent': -0.0009306778,
 'twoHundredDayAverageChange': 9.428207,
 'twoHundredDayAverageChangePercent': 0.03753091,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.9 - Buy',
 'cryptoTradeable': False,
 'marketState': 'REGULAR',
 'shortName': 'Apple Inc.',
 'longName': 'Apple Inc.',
 'displayName': 'Apple',
 'trailingPegRatio': 2.3167}

## Parsing Our API Call

This API call has all the information we need. We can parse it using the same square-bracket notation as in the first project of this course. Here is an example.

In [6]:
data['currentPrice']

260.645

## Executing A Batch API Call & Building Our DataFrame

Just like in our first project, it's now time to execute several batch API calls and add the information we need to our DataFrame.

We'll start by running the following code cell, which contains some code we already built last time that we can re-use for this project. More specifically, it contains a function called `chunks` that we can use to divide our list of securities into groups of 100.

In [7]:
# Function sourced from 
# https://stackoverflow.com/questions/312443/how-do-you-split-a-list-into-evenly-sized-chunks
def chunks(lst, n):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i:i + n]   
        
symbol_groups = list(chunks(stocks['Ticker'], 100))
symbol_strings = []
for i in range(0, len(symbol_groups)):
    symbol_strings.append(','.join(symbol_groups[i]))
#     print(symbol_strings[i])

my_columns = ['Ticker', 'Price', 'One-Year Price Return', 'Number of Shares to Buy']

Now we need to create a blank DataFrame and add our data to the data frame one-by-one.

In [8]:
final_dataframe = pd.DataFrame(columns = my_columns)
rows = []

for symbol_group in symbol_groups:
    tickers = yf.Tickers(' '.join(symbol_group))  # replaces batch_api_call_url
    
    for symbol in symbol_group:           # replaces symbol_string.split(',')
        try:
            data = tickers.tickers[symbol].info
            rows.append([
                symbol,
                data.get('currentPrice', 'N/A'),        # replaces data[symbol]['price']
                data.get('52WeekChange', 'N/A'),         # replaces data[symbol]['price']['year1ChangePercent']
                'N/A'
            ])
        except Exception as e:
            print(f"Skipping {symbol}: {e}")

final_dataframe = pd.DataFrame(rows, columns=my_columns)
final_dataframe

HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ANSS"}}}
HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CMA"}}}
HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: COG"}}}
HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: FRC"}}}
HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HBI"}}}
HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HES"}}}
HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: IPG"}}}
HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: JNPR"}}}
HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: K"}}}
HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: NLSN"}}}
HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TWTR"}}}
HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: WBA"}}}

    Ticker    Price One-Year Price Return Number of Shares to Buy
0        A    121.5              0.172249                     N/A
1      AAL   12.175              0.287686                     N/A
2      AAP   55.775              0.813795                     N/A
3     AAPL   260.75              0.332321                     N/A
4     ABBV  206.995               0.22472                     N/A
..     ...      ...                   ...                     ...
500    YUM   161.22              0.133268                     N/A
501    ZBH   95.235             -0.004333                     N/A
502   ZBRA   228.59              0.008631                     N/A
503   ZION    61.67               0.42274                     N/A
504    ZTS  120.345             -0.174775                     N/A

[505 rows x 4 columns]

## Removing Low-Momentum Stocks

The investment strategy that we're building seeks to identify the 50 highest-momentum stocks in the S&P 500.

Because of this, the next thing we need to do is remove all the stocks in our DataFrame that fall below this momentum threshold. We'll sort the DataFrame by the stocks' one-year price return, and drop all stocks outside the top 50.

In [9]:
final_dataframe['One-Year Price Return'] = pd.to_numeric(final_dataframe['One-Year Price Return'], errors='coerce')

final_dataframe.sort_values('One-Year Price Return', ascending=False, inplace=True)
final_dataframe = final_dataframe[:50]
final_dataframe.reset_index(inplace = True)
final_dataframe

    index Ticker     Price  One-Year Price Return Number of Shares to Buy
0     479    WDC    360.28               9.281302                     N/A
1     422    STX    510.53               6.325460                     N/A
2     324     MU    450.64               5.716573                     N/A
3     202    GLW    168.86               3.186531                     N/A
4     288   LRCX   264.735               3.181916                     N/A
5      23    ALB     188.4               2.611566                     N/A
6     242   INTC    65.335               2.318253                     N/A
7      31    AMD    257.29               1.889002                     N/A
8     194    FTI     71.56               1.881152                     N/A
9      29   AMAT    387.94               1.863015                     N/A
10    266   KLAC   1731.83               1.796540                     N/A
11     79    CAT    774.84               1.737472                     N/A
12    263   KEYS    325.39               1.451666                     N/A
13     42    APA    36.655               1.409239                     N/A
14    246   IPGP     125.4               1.404978                     N/A
15    441    TPR     150.9               1.399714                     N/A
16     44    APH    147.54               1.296125                     N/A
17    272    KSS     13.98               1.221860                     N/A
18    385    PWR   587.705               1.205975                     N/A
19    468    VLO    234.52               1.199011                     N/A
20    102    CMI     599.0               1.194041                     N/A
21     50   AVGO   396.165               1.180746                     N/A
22    205  GOOGL    334.24               1.171199                     N/A
23     37   ANET    154.13               1.147906                     N/A
24    331    NEM    114.87               1.132261                     N/A
25    204   GOOG  331.4861               1.125916                     N/A
26     75      C    132.17               1.086634                     N/A
27    233    HWM    254.01               1.082062                     N/A
28     73    BWA    52.385               1.063413                     N/A
29    179    FCX     68.89               1.048920                     N/A
30     10    ADI    344.75               0.981470                     N/A
31    299   MCHP      74.5               0.963109                     N/A
32    253    IVZ     24.76               0.955696                     N/A
33    187    FLS    79.615               0.935056                     N/A
34    127     DD    45.995               0.882957                     N/A
35    345   NVDA   199.345               0.880658                     N/A
36     92   CHRW   167.195               0.875250                     N/A
37    433    TEL    233.26               0.866667                     N/A
38    256    JCI    138.72               0.852987                     N/A
39    221    HII   397.035               0.846336                     N/A
40    397     RL  368.2225               0.846078                     N/A
41    255   JBHT    226.35               0.840856                     N/A
42     90    CFG     64.91               0.829385                     N/A
43    466    VFC    19.505               0.823472                     N/A
44    210     GS    908.58               0.822723                     N/A
45    180    FDX    363.42               0.818334                     N/A
46      2    AAP    55.775               0.813795                     N/A
47    315    MPC    222.11               0.804868                     N/A
48    203     GM     78.34               0.796925                     N/A
49    213    HAS    92.415               0.787779                     N/A

## Calculating the Number of Shares to Buy

Just like in the last project, we now need to calculate the number of shares we need to buy. The one change we're going to make is wrapping this functionality inside a function, since we'll be using it again later in this Jupyter Notebook.

Since we've already done most of the work on this, try to complete the following two code cells without watching me do it first!

In [10]:
def portfolio_input():
    global portfolio_size
    portfolio_size = input('Enter the size of your portfolio:')

    try:
        float(portfolio_size)
    except ValueError:
        print('That is not a number! \nPlease try again:')
        portfolio_size = input('Enter the size of your portfolio: ')

portfolio_input()
print(portfolio_size)

10000000

In [11]:
final_dataframe['Number of Shares to Buy'] = 0.0

position_size = float(portfolio_size) / len(final_dataframe.index)
for i in range(0, len(final_dataframe)):
    final_dataframe.loc[i, 'Number of Shares to Buy'] = math.floor(position_size / final_dataframe.loc[i, 'Price'])

final_dataframe

    index Ticker     Price  One-Year Price Return  Number of Shares to Buy
0     479    WDC    360.28               9.281302                    555.0
1     422    STX    510.53               6.325460                    391.0
2     324     MU    450.64               5.716573                    443.0
3     202    GLW    168.86               3.186531                   1184.0
4     288   LRCX   264.735               3.181916                    755.0
5      23    ALB     188.4               2.611566                   1061.0
6     242   INTC    65.335               2.318253                   3061.0
7      31    AMD    257.29               1.889002                    777.0
8     194    FTI     71.56               1.881152                   2794.0
9      29   AMAT    387.94               1.863015                    515.0
10    266   KLAC   1731.83               1.796540                    115.0
11     79    CAT    774.84               1.737472                    258.0
12    263   KEYS    325.39               1.451666                    614.0
13     42    APA    36.655               1.409239                   5456.0
14    246   IPGP     125.4               1.404978                   1594.0
15    441    TPR     150.9               1.399714                   1325.0
16     44    APH    147.54               1.296125                   1355.0
17    272    KSS     13.98               1.221860                  14306.0
18    385    PWR   587.705               1.205975                    340.0
19    468    VLO    234.52               1.199011                    852.0
20    102    CMI     599.0               1.194041                    333.0
21     50   AVGO   396.165               1.180746                    504.0
22    205  GOOGL    334.24               1.171199                    598.0
23     37   ANET    154.13               1.147906                   1297.0
24    331    NEM    114.87               1.132261                   1741.0
25    204   GOOG  331.4861               1.125916                    603.0
26     75      C    132.17               1.086634                   1513.0
27    233    HWM    254.01               1.082062                    787.0
28     73    BWA    52.385               1.063413                   3817.0
29    179    FCX     68.89               1.048920                   2903.0
30     10    ADI    344.75               0.981470                    580.0
31    299   MCHP      74.5               0.963109                   2684.0
32    253    IVZ     24.76               0.955696                   8077.0
33    187    FLS    79.615               0.935056                   2512.0
34    127     DD    45.995               0.882957                   4348.0
35    345   NVDA   199.345               0.880658                   1003.0
36     92   CHRW   167.195               0.875250                   1196.0
37    433    TEL    233.26               0.866667                    857.0
38    256    JCI    138.72               0.852987                   1441.0
39    221    HII   397.035               0.846336                    503.0
40    397     RL  368.2225               0.846078                    543.0
41    255   JBHT    226.35               0.840856                    883.0
42     90    CFG     64.91               0.829385                   3081.0
43    466    VFC    19.505               0.823472                  10253.0
44    210     GS    908.58               0.822723                    220.0
45    180    FDX    363.42               0.818334                    550.0
46      2    AAP    55.775               0.813795                   3585.0
47    315    MPC    222.11               0.804868                    900.0
48    203     GM     78.34               0.796925                   2552.0
49    213    HAS    92.415               0.787779                   2164.0

## Building a Better (and More Realistic) Momentum Strategy

Real-world quantitative investment firms differentiate between "high quality" and "low quality" momentum stocks:

* High-quality momentum stocks show "slow and steady" outperformance over long periods of time
* Low-quality momentum stocks might not show any momentum for a long time, and then surge upwards.

The reason why high-quality momentum stocks are preferred is because low-quality momentum can often be cause by short-term news that is unlikely to be repeated in the future (such as an FDA approval for a biotechnology company).

To identify high-quality momentum, we're going to build a strategy that selects stocks from the highest percentiles of: 

* 1-month price returns
* 3-month price returns
* 6-month price returns
* 1-year price returns

Let's start by building our DataFrame. You'll notice that I use the abbreviation `hqm` often. It stands for `high-quality momentum`.

In [15]:
stocks = pd.read_csv('sp_500_stocks.csv')

hqm_columns = [
    'Ticker', 
    'Price', 
    'Number of Shares to Buy', 
    'One-Year Price Return', 
    'One-Year Return Percentile',
    'Six-Month Price Return',
    'Six-Month Return Percentile',
    'Three-Month Price Return',
    'Three-Month Return Percentile',
    'One-Month Price Return',
    'One-Month Return Percentile',
    'HQM Score'
]

# Download all historical data in one call
all_history = yf.download(
    stocks['Ticker'].tolist(),
    period='2y',
    group_by='ticker',
    auto_adjust=True,
    threads=True
)

# Helper function to calculate returns
def get_return(hist, days):
    if len(hist) >= days:
        return (hist.iloc[-1] - hist.iloc[-days]) / hist.iloc[-days]
    return None

# Build hqm dataframe
rows = []

for symbol in stocks['Ticker']:
    try:
        ticker = yf.Ticker(symbol)
        data = ticker.info
        
        hist = all_history[symbol]['Close'].dropna()
        
        rows.append([
            symbol,
            data.get('currentPrice', None),
            None,
            get_return(hist, 252), None,  # One-Year
            get_return(hist, 126), None,  # Six-Month
            get_return(hist, 63),  None,  # Three-Month
            get_return(hist, 21),  None,  # One-Month
            None
        ])
        print(f"Fetched: {symbol}")
    except Exception as e:
        print(f"Skipping {symbol}: {e}")

hqm_dataframe = pd.DataFrame(rows, columns=hqm_columns)
hqm_dataframe

[*****                 11%                       ]  55 of 505 completed$DFS: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[******                12%                       ]  63 of 505 completed$DISCA: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[*******               14%                       ]  73 of 505 completed$ANSS: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[********              17%                       ]  84 of 505 completed$HES: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[*********             19%                       ]  96 of 505 completed$DISCK: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[*********             19%                       ]  98 of 505 completed$NLOK: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[************          24%                       ]  120 of 505 completed$DISH: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[************          26%                       ]  131 of 505 completed$HFC: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[************          26%                       ]  132 of 505 completed$CMA: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[*************         27%                       ]  138 of 505 completed$WRK: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[*************         28%                       ]  139 of 505 completed$TWTR: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[***************       32%                       ]  161 of 505 completed$PKI: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[****************      33%                       ]  165 of 505 completed$CTL: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[******************    38%                       ]  191 of 505 completed$PBCT: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[*******************   39%                       ]  199 of 505 completed$WBA: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[*******************   40%                       ]  200 of 505 completed$BF.B: possibly delisted; no price data found  (period=2y)
[********************  41%                       ]  207 of 505 completed$BLL: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[********************* 44%                       ]  222 of 505 completed$VAR: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************47%                       ]  237 of 505 completed$PXD: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************50%                       ]  250 of 505 completed$ABC: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************50%                       ]  251 of 505 completed$MXIM: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************53%                       ]  269 of 505 completed$WLTW: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************54%*                      ]  273 of 505 completed$ETFC: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************54%*                      ]  275 of 505 completed$SIVB: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************55%*                      ]  280 of 505 completed$ABMD: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$XLNX: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************57%**                     ]  287 of 505 completed$RE: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************58%***                    ]  291 of 505 completed$CERN: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************58%***                    ]  292 of 505 completed$MMC: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************59%***                    ]  299 of 505 completed$BRK.B: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************61%****                   ]  307 of 505 completed$MYL: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************65%******                 ]  330 of 505 completed$PEAK: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************66%*******                ]  335 of 505 completed$NLSN: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************67%*******                ]  337 of 505 completed$ALXN: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************68%********               ]  343 of 505 completed$K: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************69%********               ]  349 of 505 completed$HBI: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************69%********               ]  350 of 505 completed$JNPR: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************71%*********              ]  357 of 505 completed$MRO: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************75%***********            ]  378 of 505 completed$ANTM: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************78%************           ]  394 of 505 completed$NBL: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************79%*************          ]  398 of 505 completed$CTXS: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************79%*************          ]  400 of 505 completed$GPS: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************81%**************         ]  411 of 505 completed$ATVI: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************87%*****************      ]  438 of 505 completed$VIAC: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************88%*****************      ]  444 of 505 completed$COG: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************89%******************     ]  448 of 505 completed$DRE: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
$KSU: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************91%*******************    ]  462 of 505 completed$CXO: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************94%********************   ]  474 of 505 completed$FLIR: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************94%********************   ]  476 of 505 completed$FLT: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************97%********************** ]  488 of 505 completed$FRC: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************97%********************** ]  489 of 505 completed$IPG: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[**********************98%********************** ]  497 of 505 completed$FBHS: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
[*********************100%***********************]  505 of 505 completed

54 Failed downloads:
['TIF']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')
['DFS', 'DISCA', 'ANSS', 'HES', 'DISCK', 'NLOK', 'DISH', 'HFC', 'CMA', 'WRK', 'TWTR', 'PKI', 'CTL', 'PBCT', 'WBA', 'BLL', 'VAR', 'PXD', 'ABC', 'MXIM', 'WLTW', 'ETFC', 'SIVB', 'ABMD', 'XLNX', 'RE', 'CERN', 'MMC', 'BRK.B', 'MYL', 'PEAK', 'NLSN', 'ALXN', 'K', 'HBI', 'JNPR', 'MRO', 'ANTM', 'NBL', 'CTXS', 'GPS', 'ATVI', 'VIAC', 'COG', 'DRE', 'KSU', 'CXO', 'FLIR', 'FLT', 'FRC', 'IPG', 'FBHS']: possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")
['BF.B']: possibly delisted; no price data found  (period=2y)

Fetched: A
Fetched: AAL
Fetched: AAP
Fetched: AAPL
Fetched: ABBV
Fetched: ABC
Fetched: ABMD
Fetched: ABT
Fetched: ACN
Fetched: ADBE
Fetched: ADI
Fetched: ADM
Fetched: ADP
Fetched: ADSK
Fetched: AEE
Fetched: AEP
Fetched: AES
Fetched: AFL
Fetched: AIG
Fetched: AIV
Fetched: AIZ
Fetched: AJG
Fetched: AKAM
Fetched: ALB
Fetched: ALGN
Fetched: ALK
Fetched: ALL
Fetched: ALLE
Fetched: ALXN
Fetched: AMAT
Fetched: AMCR
Fetched: AMD
Fetched: AME
Fetched: AMGN
Fetched: AMP
Fetched: AMT
Fetched: AMZN
Fetched: ANET

HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ANSS"}}}

Fetched: ANSS
Fetched: ANTM
Fetched: AON
Fetched: AOS
Fetched: APA
Fetched: APD
Fetched: APH
Fetched: APTV
Fetched: ARE
Fetched: ATO
Fetched: ATVI
Fetched: AVB
Fetched: AVGO
Fetched: AVY
Fetched: AWK
Fetched: AXP
Fetched: AZO
Fetched: BA
Fetched: BAC
Fetched: BAX
Fetched: BBY
Fetched: BDX
Fetched: BEN
Fetched: BF.B
Fetched: BIIB
Fetched: BIO
Fetched: BK
Fetched: BKNG
Fetched: BKR
Fetched: BLK
Fetched: BLL
Fetched: BMY
Fetched: BR
Fetched: BRK.B
Fetched: BSX
Fetched: BWA
Fetched: BXP
Fetched: C
Fetched: CAG
Fetched: CAH
Fetched: CARR
Fetched: CAT
Fetched: CB
Fetched: CBOE
Fetched: CBRE
Fetched: CCI
Fetched: CCL
Fetched: CDNS
Fetched: CDW
Fetched: CE
Fetched: CERN
Fetched: CF
Fetched: CFG
Fetched: CHD
Fetched: CHRW
Fetched: CHTR
Fetched: CI
Fetched: CINF
Fetched: CL
Fetched: CLX

HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CMA"}}}

Fetched: CMA
Fetched: CMCSA
Fetched: CME
Fetched: CMG
Fetched: CMI
Fetched: CMS
Fetched: CNC
Fetched: CNP
Fetched: COF

HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: COG"}}}

Fetched: COG
Fetched: COO
Fetched: COP
Fetched: COST
Fetched: COTY
Fetched: CPB
Fetched: CPRT
Fetched: CRM
Fetched: CSCO
Fetched: CSX
Fetched: CTAS
Fetched: CTL
Fetched: CTSH
Fetched: CTVA
Fetched: CTXS
Fetched: CVS
Fetched: CVX
Fetched: CXO
Fetched: D
Fetched: DAL
Fetched: DD
Fetched: DE
Fetched: DFS
Fetched: DG
Fetched: DGX
Fetched: DHI
Fetched: DHR
Fetched: DIS
Fetched: DISCA
Fetched: DISCK
Fetched: DISH
Fetched: DLR
Fetched: DLTR
Fetched: DOV
Fetched: DOW
Fetched: DPZ
Fetched: DRE
Fetched: DRI
Fetched: DTE
Fetched: DUK
Fetched: DVA
Fetched: DVN
Fetched: DXC
Fetched: DXCM
Fetched: EA
Fetched: EBAY
Fetched: ECL
Fetched: ED
Fetched: EFX
Fetched: EIX
Fetched: EL
Fetched: EMN
Fetched: EMR
Fetched: EOG
Fetched: EQIX
Fetched: EQR
Fetched: ES
Fetched: ESS
Fetched: ETFC
Fetched: ETN
Fetched: ETR
Fetched: EVRG
Fetched: EW
Fetched: EXC
Fetched: EXPD
Fetched: EXPE
Fetched: EXR
Fetched: F
Fetched: FANG
Fetched: FAST
Fetched: FB
Fetched: FBHS
Fetched: FCX
Fetched: FDX
Fetched: FE
Fetched: FFIV
Fetched: FIS
Fetched: FISV
Fetched: FITB
Fetched: FLIR
Fetched: FLS
Fetched: FLT
Fetched: FMC
Fetched: FOX
Fetched: FOXA

HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: FRC"}}}

Fetched: FRC
Fetched: FRT
Fetched: FTI
Fetched: FTNT
Fetched: FTV
Fetched: GD
Fetched: GE
Fetched: GILD
Fetched: GIS
Fetched: GL
Fetched: GLW
Fetched: GM
Fetched: GOOG
Fetched: GOOGL
Fetched: GPC
Fetched: GPN
Fetched: GPS
Fetched: GRMN
Fetched: GS
Fetched: GWW
Fetched: HAL
Fetched: HAS
Fetched: HBAN

HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HBI"}}}

Fetched: HBI
Fetched: HCA
Fetched: HD

HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HES"}}}

Fetched: HES
Fetched: HFC
Fetched: HIG
Fetched: HII
Fetched: HLT
Fetched: HOLX
Fetched: HON
Fetched: HPE
Fetched: HPQ
Fetched: HRB
Fetched: HRL
Fetched: HSIC
Fetched: HST
Fetched: HSY
Fetched: HUM
Fetched: HWM
Fetched: IBM
Fetched: ICE
Fetched: IDXX
Fetched: IEX
Fetched: IFF
Fetched: ILMN
Fetched: INCY
Fetched: INFO
Fetched: INTC
Fetched: INTU
Fetched: IP

HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: IPG"}}}

Fetched: IPG
Fetched: IPGP
Fetched: IQV
Fetched: IR
Fetched: IRM
Fetched: ISRG
Fetched: IT
Fetched: ITW
Fetched: IVZ
Fetched: J
Fetched: JBHT
Fetched: JCI
Fetched: JKHY
Fetched: JNJ

HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: JNPR"}}}

Fetched: JNPR
Fetched: JPM

HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: K"}}}

Fetched: K
Fetched: KEY
Fetched: KEYS
Fetched: KHC
Fetched: KIM
Fetched: KLAC
Fetched: KMB
Fetched: KMI
Fetched: KMX
Fetched: KO
Fetched: KR
Fetched: KSS
Fetched: KSU
Fetched: L
Fetched: LB
Fetched: LDOS
Fetched: LEG
Fetched: LEN
Fetched: LH
Fetched: LHX
Fetched: LIN
Fetched: LKQ
Fetched: LLY
Fetched: LMT
Fetched: LNC
Fetched: LNT
Fetched: LOW
Fetched: LRCX
Fetched: LUV
Fetched: LVS
Fetched: LW
Fetched: LYB
Fetched: LYV
Fetched: MA
Fetched: MAA
Fetched: MAR
Fetched: MAS
Fetched: MCD
Fetched: MCHP
Fetched: MCK
Fetched: MCO
Fetched: MDLZ
Fetched: MDT
Fetched: MET
Fetched: MGM
Fetched: MHK
Fetched: MKC
Fetched: MKTX
Fetched: MLM
Fetched: MMC
Fetched: MMM
Fetched: MNST
Fetched: MO
Fetched: MOS
Fetched: MPC
Fetched: MRK
Fetched: MRO
Fetched: MS
Fetched: MSCI
Fetched: MSFT
Fetched: MSI
Fetched: MTB
Fetched: MTD
Fetched: MU
Fetched: MXIM
Fetched: MYL
Fetched: NBL
Fetched: NCLH
Fetched: NDAQ
Fetched: NEE
Fetched: NEM
Fetched: NFLX
Fetched: NI
Fetched: NKE
Fetched: NLOK

HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: NLSN"}}}

Fetched: NLSN
Fetched: NOC
Fetched: NOV
Fetched: NOW
Fetched: NRG
Fetched: NSC
Fetched: NTAP
Fetched: NTRS
Fetched: NUE
Fetched: NVDA
Fetched: NVR
Fetched: NWL
Fetched: NWS
Fetched: NWSA
Fetched: O
Fetched: ODFL
Fetched: OKE
Fetched: OMC
Fetched: ORCL
Fetched: ORLY
Fetched: OTIS
Fetched: OXY
Fetched: PAYC
Fetched: PAYX
Fetched: PBCT
Fetched: PCAR
Fetched: PEAK
Fetched: PEG
Fetched: PEP
Fetched: PFE
Fetched: PFG
Fetched: PG
Fetched: PGR
Fetched: PH
Fetched: PHM
Fetched: PKG
Fetched: PKI
Fetched: PLD
Fetched: PM
Fetched: PNC
Fetched: PNR
Fetched: PNW
Fetched: PPG
Fetched: PPL
Fetched: PRGO
Fetched: PRU
Fetched: PSA
Fetched: PSX
Fetched: PVH
Fetched: PWR
Fetched: PXD
Fetched: PYPL
Fetched: QCOM
Fetched: QRVO
Fetched: RCL
Fetched: RE
Fetched: REG
Fetched: REGN
Fetched: RF
Fetched: RHI
Fetched: RJF
Fetched: RL
Fetched: RMD
Fetched: ROK
Fetched: ROL
Fetched: ROP
Fetched: ROST
Fetched: RSG
Fetched: RTX
Fetched: SBAC
Fetched: SBUX
Fetched: SCHW
Fetched: SEE
Fetched: SHW
Fetched: SIVB
Fetched: SJM
Fetched: SLB
Fetched: SLG
Fetched: SNA
Fetched: SNPS
Fetched: SO
Fetched: SPG
Fetched: SPGI
Fetched: SRE
Fetched: STE
Fetched: STT
Fetched: STX
Fetched: STZ
Fetched: SWK
Fetched: SWKS
Fetched: SYF
Fetched: SYK
Fetched: SYY
Fetched: T
Fetched: TAP
Fetched: TDG
Fetched: TDY
Fetched: TEL
Fetched: TFC
Fetched: TFX
Fetched: TGT
Fetched: TIF
Fetched: TJX
Fetched: TMO
Fetched: TMUS
Fetched: TPR
Fetched: TROW
Fetched: TRV
Fetched: TSCO
Fetched: TSN
Fetched: TT
Fetched: TTWO

HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TWTR"}}}

Fetched: TWTR
Fetched: TXN
Fetched: TXT
Fetched: TYL
Fetched: UA
Fetched: UAA
Fetched: UAL
Fetched: UDR
Fetched: UHS
Fetched: ULTA
Fetched: UNH
Fetched: UNM
Fetched: UNP
Fetched: UPS
Fetched: URI
Fetched: USB
Fetched: V
Fetched: VAR
Fetched: VFC
Fetched: VIAC
Fetched: VLO
Fetched: VMC
Fetched: VNO
Fetched: VRSK
Fetched: VRSN
Fetched: VRTX
Fetched: VTR
Fetched: VZ
Fetched: WAB
Fetched: WAT

HTTP Error 404: Not Found{"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: WBA"}}}

Fetched: WBA
Fetched: WDC
Fetched: WEC
Fetched: WELL
Fetched: WFC
Fetched: WHR
Fetched: WLTW
Fetched: WM
Fetched: WMB
Fetched: WMT
Fetched: WRB
Fetched: WRK
Fetched: WST
Fetched: WU
Fetched: WY
Fetched: WYNN
Fetched: XEL
Fetched: XLNX
Fetched: XOM
Fetched: XRAY
Fetched: XRX
Fetched: XYL
Fetched: YUM
Fetched: ZBH
Fetched: ZBRA
Fetched: ZION
Fetched: ZTS

,Ticker,Price,Number of Shares to Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile,HQM Score
0,A,121.4250,None,0.163863,None,-0.116744,None,-0.165933,None,0.079442,None,None
1,AAL,12.1201,None,0.265658,None,-0.005332,None,-0.199141,None,0.116483,None,None
2,AAP,56.1600,None,0.741720,None,0.033216,None,0.315519,None,0.086469,None,None
3,AAPL,263.0039,None,0.304049,None,0.063289,None,0.012448,None,0.034300,None,None
4,ABBV,206.1650,None,0.191463,None,-0.085120,None,-0.062030,None,-0.060498,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
500,YUM,161.0500,None,0.124307,None,0.129035,None,0.029671,None,-0.016128,None,None
501,ZBH,95.5300,None,-0.053955,None,-0.024258,None,0.072717,None,0.034687,None,None
502,ZBRA,229.1350,None,-0.011520,None,-0.207239,None,-0.127271,None,0.095858,None,None
503,ZION,61.7600,None,0.488022,None,0.135398,None,0.058259,None,0.143465,None,None
504,ZTS,120.4750,None,-0.189666,None,-0.153732,None,-0.038585,None,-0.009944,None,None

## Calculating Momentum Percentiles

We now need to calculate momentum percentile scores for every stock in the universe. More specifically, we need to calculate percentile scores for the following metrics for every stock:

* `One-Year Price Return`
* `Six-Month Price Return`
* `Three-Month Price Return`
* `One-Month Price Return`

Here's how we'll do this:

In [35]:
from scipy.stats import percentileofscore as score

time_periods = [
    'One-Year',
    'Six-Month',
    'Three-Month',
    'One-Month'
]

# Convert return columns to numeric first
for time_period in time_periods:
    hqm_dataframe[f'{time_period} Price Return'] = pd.to_numeric(
        hqm_dataframe[f'{time_period} Price Return'], errors='coerce'
    )

for row in hqm_dataframe.index:
    for time_period in time_periods:
        hqm_dataframe.loc[row, f'{time_period} Return Percentile'] = score(
            hqm_dataframe[f'{time_period} Price Return'].dropna(),
            hqm_dataframe.loc[row, f'{time_period} Price Return']
        ) / 100

# Print each percentile score to make sure it was calculated properly
for time_period in time_periods:
    print(hqm_dataframe[f'{time_period} Return Percentile'])

hqm_dataframe

0     0.98
1     0.94
2      1.0
3     0.88
4     0.92
5     0.72
6     0.78
7     0.86
8     0.82
9     0.56
10    0.62
11     0.8
12     0.7
13    0.52
14    0.84
15     0.9
16     0.2
17    0.28
18    0.32
19    0.68
20    0.76
21    0.46
22    0.26
23     0.1
24    0.22
25     0.5
26    0.58
27    0.02
28    0.24
29    0.64
30    0.44
31    0.16
32    0.18
33     0.6
34    0.54
35    0.14
36    0.74
37    0.42
38     0.4
39    0.36
40    0.06
41    0.38
42    0.12
43    0.04
44    0.34
45    0.48
46    0.08
47    0.96
48    0.66
49     0.3
Name: One-Year Return Percentile, dtype: object
0     0.98
1     0.92
2      1.0
3     0.82
4     0.86
5      0.9
6     0.76
7     0.94
8      0.8
9     0.74
10    0.34
11    0.52
12    0.56
13    0.54
14    0.06
15    0.88
16    0.68
17    0.64
18    0.44
19    0.04
20     0.7
21    0.78
22    0.66
23    0.84
24    0.36
25     0.2
26    0.02
27    0.58
28    0.42
29     0.4
30    0.16
31    0.48
32    0.24
33    0.46
34     0.3
35    0.32
36    0.28
37    0.14
38     0.1
39    0.22
40    0.72
41    0.38
42    0.18
43    0.26
44    0.62
45     0.6
46    0.08
47    0.96
48     0.5
49    0.12
Name: Six-Month Return Percentile, dtype: object
0     0.96
1      1.0
2     0.98
3     0.76
4      0.7
5     0.92
6     0.56
7     0.84
8     0.72
9     0.34
10    0.52
11    0.58
12    0.94
13    0.48
14    0.38
15    0.12
16    0.26
17    0.82
18    0.22
19    0.46
20    0.86
21     0.4
22     0.2
23    0.88
24    0.28
25    0.18
26    0.62
27    0.54
28    0.64
29    0.78
30    0.14
31     0.5
32    0.32
33     0.1
34    0.42
35    0.36
36     0.3
37    0.06
38    0.16
39    0.66
40     0.9
41    0.02
42    0.24
43    0.74
44    0.44
45    0.08
46     0.6
47     0.8
48    0.68
49    0.04
Name: Three-Month Return Percentile, dtype: object
0     0.92
1     0.96
2     0.72
3      1.0
4     0.78
5     0.64
6     0.76
7     0.44
8     0.42
9     0.86
10    0.88
11    0.48
12    0.34
13    0.46
14    0.98
15    0.62
16    0.68
17     0.3
18     0.8
19    0.94
20    0.08
21    0.22
22    0.58
23    0.26
24    0.54
25    0.66
26    0.74
27    0.56
28    0.24
29     0.1
30     0.9
31    0.28
32     0.5
33     0.4
34    0.18
35    0.38
36    0.16
37    0.82
38     0.7
39    0.14
40    0.12
41    0.84
42    0.52
43    0.32
44    0.06
45     0.2
46    0.36
47    0.02
48    0.04
49     0.6
Name: One-Month Return Percentile, dtype: object

,level_0,index,Ticker,Price,Number of Shares to Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile,HQM Score
0,0,422,STX,513.3500,0,6.163813,0.98,1.439244,0.98,0.648734,0.96,0.222700,0.92,0.994456
1,1,202,GLW,168.3016,0,3.109083,0.94,1.001301,0.92,0.870684,1.0,0.296790,0.96,0.994453
2,2,479,WDC,360.0900,0,9.080735,1.0,2.182192,1.0,0.673080,0.98,0.145725,0.72,0.987251
3,3,242,INTC,65.3300,1,2.216741,0.88,0.833623,0.82,0.340969,0.76,0.482796,1.0,0.983917
4,4,288,LRCX,264.0300,0,2.921391,0.92,0.915421,0.86,0.266759,0.7,0.166468,0.78,0.975051
5,5,263,KEYS,325.4900,0,1.386465,0.72,0.974581,0.9,0.554394,0.92,0.132612,0.64,0.968941
6,6,266,KLAC,1725.3900,0,1.596550,0.78,0.688259,0.76,0.205133,0.56,0.165504,0.76,0.960075
7,7,194,FTI,72.0100,1,1.849814,0.86,1.002802,0.94,0.378187,0.84,0.101010,0.44,0.953428
8,8,29,AMAT,387.4200,0,1.704530,0.82,0.781308,0.8,0.284916,0.72,0.099189,0.42,0.942894
9,9,179,FCX,68.7900,1,1.068530,0.56,0.650564,0.74,0.143771,0.34,0.185316,0.86,0.938438
10,10,75,C,131.3500,0,1.131513,0.62,0.330246,0.34,0.174491,0.52,0.219385,0.88,0.931792
11,11,79,CAT,774.0700,0,1.631560,0.8,0.474798,0.52,0.214377,0.58,0.102382,0.48,0.929034
12,12,246,IPGP,124.7200,0,1.288440,0.7,0.499039,0.56,0.608460,0.94,0.079827,0.34,0.925702
13,13,10,ADI,345.5950,0,0.964545,0.52,0.477917,0.54,0.163385,0.48,0.101814,0.46,0.909051
14,14,31,AMD,256.6700,0,1.715979,0.84,0.176854,0.06,0.147853,0.38,0.307422,0.98,0.893006
15,15,23,ALB,187.9450,0,2.332362,0.9,0.963625,0.88,0.061169,0.12,0.130020,0.62,0.892455
16,16,412,SLB,52.5950,1,0.599628,0.2,0.638897,0.68,0.127538,0.26,0.141340,0.68,0.890145
17,17,87,CE,64.4760,1,0.649277,0.28,0.581508,0.64,0.373786,0.82,0.071386,0.3,0.887389
18,18,344,NUE,189.1100,0,0.733852,0.32,0.375844,0.44,0.102331,0.22,0.171770,0.8,0.883517
19,19,50,AVGO,394.2800,0,1.227451,0.68,0.149790,0.04,0.161910,0.46,0.229099,0.94,0.880798
20,20,42,APA,36.8900,2,1.552023,0.76,0.643480,0.7,0.395101,0.86,0.028283,0.08,0.875817
21,21,212,HAL,37.7150,2,0.825899,0.46,0.701837,0.78,0.148546,0.4,0.059624,0.22,0.869685
22,22,255,JBHT,224.7900,0,0.649075,0.26,0.620420,0.66,0.094456,0.2,0.123326,0.58,0.869095
23,23,141,DOW,39.3850,2,0.456407,0.1,0.845519,0.84,0.410531,0.88,0.067326,0.26,0.867938
24,24,296,MAR,362.4400,0,0.637082,0.22,0.358374,0.36,0.135965,0.28,0.107446,0.54,0.865207
25,25,90,CFG,64.9450,1,0.893425,0.5,0.275260,0.2,0.092383,0.18,0.138728,0.66,0.863041
26,26,37,ANET,152.6900,0,1.073753,0.58,0.099557,0.02,0.219982,0.62,0.146821,0.74,0.860834
27,27,351,ODFL,206.0350,0,0.337373,0.02,0.526226,0.58,0.188841,0.54,0.116955,0.56,0.858468
28,28,66,BKR,60.7900,1,0.640884,0.24,0.368044,0.42,0.221277,0.64,0.066842,0.24,0.856895
29,29,385,PWR,587.9600,0,1.145512,0.64,0.362874,0.4,0.345466,0.78,0.028730,0.1,0.854743
30,30,318,MS,192.8800,0,0.812655,0.44,0.254351,0.16,0.071312,0.14,0.220364,0.9,0.85028
31,31,402,ROST,223.5000,0,0.572226,0.16,0.446740,0.48,0.168275,0.5,0.069052,0.28,0.849674
32,32,230,HST,20.5350,3,0.574794,0.18,0.293006,0.24,0.140183,0.32,0.105007,0.5,0.84912
33,33,102,CMI,596.8350,0,1.106655,0.6,0.443447,0.46,0.059532,0.1,0.098570,0.4,0.84864
34,34,233,HWM,253.6100,0,0.995040,0.54,0.315642,0.3,0.152374,0.42,0.055882,0.18,0.846417
35,35,476,WAB,259.0550,0,0.503625,0.14,0.325953,0.32,0.144659,0.36,0.089419,0.38,0.841899
36,36,441,TPR,150.8850,0,1.399963,0.74,0.305843,0.28,0.136063,0.3,0.053961,0.16,0.839784
37,37,421,STT,141.5600,0,0.798171,0.42,0.242672,0.14,0.057531,0.06,0.172019,0.82,0.833644
38,38,343,NTRS,156.4500,0,0.786468,0.4,0.227160,0.1,0.082748,0.16,0.144090,0.7,0.833088
39,39,256,JCI,138.2150,0,0.772542,0.36,0.285499,0.22,0.236431,0.66,0.042660,0.14,0.833085
40,40,292,LYB,73.8000,1,0.405559,0.06,0.649257,0.72,0.438506,0.9,0.037992,0.12,0.828559
41,41,466,VFC,19.4900,4,0.772882,0.38,0.362230,0.38,0.018546,0.02,0.176920,0.84,0.828097
42,42,449,TXN,214.9900,0,0.470705,0.12,0.256691,0.18,0.119953,0.24,0.106968,0.52,0.823597
43,43,161,EQIX,1048.8100,0,0.369786,0.04,0.298609,0.26,0.320517,0.74,0.074236,0.32,0.822448
44,44,180,FDX,362.8699,0,0.760977,0.34,0.559107,0.62,0.160931,0.44,0.022218,0.06,0.818114
45,45,187,FLS,79.2600,1,0.891617,0.48,0.556194,0.6,0.058151,0.08,0.058433,0.2,0.813705
46,46,167,ETR,115.0500,0,0.431647,0.08,0.206287,0.08,0.217051,0.6,0.084850,0.36,0.81305
47,47,324,MU,452.4700,0,5.381897,0.96,1.419185,0.96,0.356982,0.8,-0.020230,0.02,0.811527
48,48,468,VLO,234.3400,0,1.189087,0.66,0.464631,0.5,0.265669,0.68,-0.005658,0.04,0.808735
49,49,64,BK,131.0750,0,0.726973,0.3,0.235602,0.12,0.057033,0.04,0.129134,0.6,0.808682

## Calculating the HQM Score

We'll now calculate our `HQM Score`, which is the high-quality momentum score that we'll use to filter for stocks in this investing strategy.

The `HQM Score` will be the arithmetic mean of the 4 momentum percentile scores that we calculated in the last section.

To calculate arithmetic mean, we will use the `mean` function from Python's built-in `statistics` module.

In [36]:
from statistics import mean

for row in hqm_dataframe.index:
    momentum_percentiles = []
    for time_period in time_periods:
        momentum_percentiles.append(hqm_dataframe.loc[row, f'{time_period} Return Percentile'])
    hqm_dataframe.loc[row, 'HQM Score'] = mean(momentum_percentiles)

hqm_dataframe

,level_0,index,Ticker,Price,Number of Shares to Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile,HQM Score
0,0,422,STX,513.3500,0,6.163813,0.98,1.439244,0.98,0.648734,0.96,0.222700,0.92,0.96
1,1,202,GLW,168.3016,0,3.109083,0.94,1.001301,0.92,0.870684,1.0,0.296790,0.96,0.955
2,2,479,WDC,360.0900,0,9.080735,1.0,2.182192,1.0,0.673080,0.98,0.145725,0.72,0.925
3,3,242,INTC,65.3300,1,2.216741,0.88,0.833623,0.82,0.340969,0.76,0.482796,1.0,0.865
4,4,288,LRCX,264.0300,0,2.921391,0.92,0.915421,0.86,0.266759,0.7,0.166468,0.78,0.815
5,5,263,KEYS,325.4900,0,1.386465,0.72,0.974581,0.9,0.554394,0.92,0.132612,0.64,0.795
6,6,266,KLAC,1725.3900,0,1.596550,0.78,0.688259,0.76,0.205133,0.56,0.165504,0.76,0.715
7,7,194,FTI,72.0100,1,1.849814,0.86,1.002802,0.94,0.378187,0.84,0.101010,0.44,0.77
8,8,29,AMAT,387.4200,0,1.704530,0.82,0.781308,0.8,0.284916,0.72,0.099189,0.42,0.69
9,9,179,FCX,68.7900,1,1.068530,0.56,0.650564,0.74,0.143771,0.34,0.185316,0.86,0.625
10,10,75,C,131.3500,0,1.131513,0.62,0.330246,0.34,0.174491,0.52,0.219385,0.88,0.59
11,11,79,CAT,774.0700,0,1.631560,0.8,0.474798,0.52,0.214377,0.58,0.102382,0.48,0.595
12,12,246,IPGP,124.7200,0,1.288440,0.7,0.499039,0.56,0.608460,0.94,0.079827,0.34,0.635
13,13,10,ADI,345.5950,0,0.964545,0.52,0.477917,0.54,0.163385,0.48,0.101814,0.46,0.5
14,14,31,AMD,256.6700,0,1.715979,0.84,0.176854,0.06,0.147853,0.38,0.307422,0.98,0.565
15,15,23,ALB,187.9450,0,2.332362,0.9,0.963625,0.88,0.061169,0.12,0.130020,0.62,0.63
16,16,412,SLB,52.5950,1,0.599628,0.2,0.638897,0.68,0.127538,0.26,0.141340,0.68,0.455
17,17,87,CE,64.4760,1,0.649277,0.28,0.581508,0.64,0.373786,0.82,0.071386,0.3,0.51
18,18,344,NUE,189.1100,0,0.733852,0.32,0.375844,0.44,0.102331,0.22,0.171770,0.8,0.445
19,19,50,AVGO,394.2800,0,1.227451,0.68,0.149790,0.04,0.161910,0.46,0.229099,0.94,0.53
20,20,42,APA,36.8900,2,1.552023,0.76,0.643480,0.7,0.395101,0.86,0.028283,0.08,0.6
21,21,212,HAL,37.7150,2,0.825899,0.46,0.701837,0.78,0.148546,0.4,0.059624,0.22,0.465
22,22,255,JBHT,224.7900,0,0.649075,0.26,0.620420,0.66,0.094456,0.2,0.123326,0.58,0.425
23,23,141,DOW,39.3850,2,0.456407,0.1,0.845519,0.84,0.410531,0.88,0.067326,0.26,0.52
24,24,296,MAR,362.4400,0,0.637082,0.22,0.358374,0.36,0.135965,0.28,0.107446,0.54,0.35
25,25,90,CFG,64.9450,1,0.893425,0.5,0.275260,0.2,0.092383,0.18,0.138728,0.66,0.385
26,26,37,ANET,152.6900,0,1.073753,0.58,0.099557,0.02,0.219982,0.62,0.146821,0.74,0.49
27,27,351,ODFL,206.0350,0,0.337373,0.02,0.526226,0.58,0.188841,0.54,0.116955,0.56,0.425
28,28,66,BKR,60.7900,1,0.640884,0.24,0.368044,0.42,0.221277,0.64,0.066842,0.24,0.385
29,29,385,PWR,587.9600,0,1.145512,0.64,0.362874,0.4,0.345466,0.78,0.028730,0.1,0.48
30,30,318,MS,192.8800,0,0.812655,0.44,0.254351,0.16,0.071312,0.14,0.220364,0.9,0.41
31,31,402,ROST,223.5000,0,0.572226,0.16,0.446740,0.48,0.168275,0.5,0.069052,0.28,0.355
32,32,230,HST,20.5350,3,0.574794,0.18,0.293006,0.24,0.140183,0.32,0.105007,0.5,0.31
33,33,102,CMI,596.8350,0,1.106655,0.6,0.443447,0.46,0.059532,0.1,0.098570,0.4,0.39
34,34,233,HWM,253.6100,0,0.995040,0.54,0.315642,0.3,0.152374,0.42,0.055882,0.18,0.36
35,35,476,WAB,259.0550,0,0.503625,0.14,0.325953,0.32,0.144659,0.36,0.089419,0.38,0.3
36,36,441,TPR,150.8850,0,1.399963,0.74,0.305843,0.28,0.136063,0.3,0.053961,0.16,0.37
37,37,421,STT,141.5600,0,0.798171,0.42,0.242672,0.14,0.057531,0.06,0.172019,0.82,0.36
38,38,343,NTRS,156.4500,0,0.786468,0.4,0.227160,0.1,0.082748,0.16,0.144090,0.7,0.34
39,39,256,JCI,138.2150,0,0.772542,0.36,0.285499,0.22,0.236431,0.66,0.042660,0.14,0.345
40,40,292,LYB,73.8000,1,0.405559,0.06,0.649257,0.72,0.438506,0.9,0.037992,0.12,0.45
41,41,466,VFC,19.4900,4,0.772882,0.38,0.362230,0.38,0.018546,0.02,0.176920,0.84,0.405
42,42,449,TXN,214.9900,0,0.470705,0.12,0.256691,0.18,0.119953,0.24,0.106968,0.52,0.265
43,43,161,EQIX,1048.8100,0,0.369786,0.04,0.298609,0.26,0.320517,0.74,0.074236,0.32,0.34
44,44,180,FDX,362.8699,0,0.760977,0.34,0.559107,0.62,0.160931,0.44,0.022218,0.06,0.365
45,45,187,FLS,79.2600,1,0.891617,0.48,0.556194,0.6,0.058151,0.08,0.058433,0.2,0.34
46,46,167,ETR,115.0500,0,0.431647,0.08,0.206287,0.08,0.217051,0.6,0.084850,0.36,0.28
47,47,324,MU,452.4700,0,5.381897,0.96,1.419185,0.96,0.356982,0.8,-0.020230,0.02,0.685
48,48,468,VLO,234.3400,0,1.189087,0.66,0.464631,0.5,0.265669,0.68,-0.005658,0.04,0.47
49,49,64,BK,131.0750,0,0.726973,0.3,0.235602,0.12,0.057033,0.04,0.129134,0.6,0.265

## Selecting the 50 Best Momentum Stocks

As before, we can identify the 50 best momentum stocks in our universe by sorting the DataFrame on the `HQM Score` column and dropping all but the top 50 entries.

In [37]:
hqm_dataframe.sort_values('HQM Score', ascending = False, inplace = True)
hqm_dataframe = hqm_dataframe[:50]
hqm_dataframe.reset_index(drop = True, inplace = True)
hqm_dataframe

,level_0,index,Ticker,Price,Number of Shares to Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile,HQM Score
0,0,422,STX,513.3500,0,6.163813,0.98,1.439244,0.98,0.648734,0.96,0.222700,0.92,0.96
1,1,202,GLW,168.3016,0,3.109083,0.94,1.001301,0.92,0.870684,1.0,0.296790,0.96,0.955
2,2,479,WDC,360.0900,0,9.080735,1.0,2.182192,1.0,0.673080,0.98,0.145725,0.72,0.925
3,3,242,INTC,65.3300,1,2.216741,0.88,0.833623,0.82,0.340969,0.76,0.482796,1.0,0.865
4,4,288,LRCX,264.0300,0,2.921391,0.92,0.915421,0.86,0.266759,0.7,0.166468,0.78,0.815
5,5,263,KEYS,325.4900,0,1.386465,0.72,0.974581,0.9,0.554394,0.92,0.132612,0.64,0.795
6,7,194,FTI,72.0100,1,1.849814,0.86,1.002802,0.94,0.378187,0.84,0.101010,0.44,0.77
7,6,266,KLAC,1725.3900,0,1.596550,0.78,0.688259,0.76,0.205133,0.56,0.165504,0.76,0.715
8,8,29,AMAT,387.4200,0,1.704530,0.82,0.781308,0.8,0.284916,0.72,0.099189,0.42,0.69
9,47,324,MU,452.4700,0,5.381897,0.96,1.419185,0.96,0.356982,0.8,-0.020230,0.02,0.685
10,12,246,IPGP,124.7200,0,1.288440,0.7,0.499039,0.56,0.608460,0.94,0.079827,0.34,0.635
11,15,23,ALB,187.9450,0,2.332362,0.9,0.963625,0.88,0.061169,0.12,0.130020,0.62,0.63
12,9,179,FCX,68.7900,1,1.068530,0.56,0.650564,0.74,0.143771,0.34,0.185316,0.86,0.625
13,20,42,APA,36.8900,2,1.552023,0.76,0.643480,0.7,0.395101,0.86,0.028283,0.08,0.6
14,11,79,CAT,774.0700,0,1.631560,0.8,0.474798,0.52,0.214377,0.58,0.102382,0.48,0.595
15,10,75,C,131.3500,0,1.131513,0.62,0.330246,0.34,0.174491,0.52,0.219385,0.88,0.59
16,14,31,AMD,256.6700,0,1.715979,0.84,0.176854,0.06,0.147853,0.38,0.307422,0.98,0.565
17,19,50,AVGO,394.2800,0,1.227451,0.68,0.149790,0.04,0.161910,0.46,0.229099,0.94,0.53
18,23,141,DOW,39.3850,2,0.456407,0.1,0.845519,0.84,0.410531,0.88,0.067326,0.26,0.52
19,17,87,CE,64.4760,1,0.649277,0.28,0.581508,0.64,0.373786,0.82,0.071386,0.3,0.51
20,13,10,ADI,345.5950,0,0.964545,0.52,0.477917,0.54,0.163385,0.48,0.101814,0.46,0.5
21,26,37,ANET,152.6900,0,1.073753,0.58,0.099557,0.02,0.219982,0.62,0.146821,0.74,0.49
22,29,385,PWR,587.9600,0,1.145512,0.64,0.362874,0.4,0.345466,0.78,0.028730,0.1,0.48
23,48,468,VLO,234.3400,0,1.189087,0.66,0.464631,0.5,0.265669,0.68,-0.005658,0.04,0.47
24,21,212,HAL,37.7150,2,0.825899,0.46,0.701837,0.78,0.148546,0.4,0.059624,0.22,0.465
25,16,412,SLB,52.5950,1,0.599628,0.2,0.638897,0.68,0.127538,0.26,0.141340,0.68,0.455
26,40,292,LYB,73.8000,1,0.405559,0.06,0.649257,0.72,0.438506,0.9,0.037992,0.12,0.45
27,18,344,NUE,189.1100,0,0.733852,0.32,0.375844,0.44,0.102331,0.22,0.171770,0.8,0.445
28,22,255,JBHT,224.7900,0,0.649075,0.26,0.620420,0.66,0.094456,0.2,0.123326,0.58,0.425
29,27,351,ODFL,206.0350,0,0.337373,0.02,0.526226,0.58,0.188841,0.54,0.116955,0.56,0.425
30,30,318,MS,192.8800,0,0.812655,0.44,0.254351,0.16,0.071312,0.14,0.220364,0.9,0.41
31,41,466,VFC,19.4900,4,0.772882,0.38,0.362230,0.38,0.018546,0.02,0.176920,0.84,0.405
32,33,102,CMI,596.8350,0,1.106655,0.6,0.443447,0.46,0.059532,0.1,0.098570,0.4,0.39
33,25,90,CFG,64.9450,1,0.893425,0.5,0.275260,0.2,0.092383,0.18,0.138728,0.66,0.385
34,28,66,BKR,60.7900,1,0.640884,0.24,0.368044,0.42,0.221277,0.64,0.066842,0.24,0.385
35,36,441,TPR,150.8850,0,1.399963,0.74,0.305843,0.28,0.136063,0.3,0.053961,0.16,0.37
36,44,180,FDX,362.8699,0,0.760977,0.34,0.559107,0.62,0.160931,0.44,0.022218,0.06,0.365
37,34,233,HWM,253.6100,0,0.995040,0.54,0.315642,0.3,0.152374,0.42,0.055882,0.18,0.36
38,37,421,STT,141.5600,0,0.798171,0.42,0.242672,0.14,0.057531,0.06,0.172019,0.82,0.36
39,31,402,ROST,223.5000,0,0.572226,0.16,0.446740,0.48,0.168275,0.5,0.069052,0.28,0.355
40,24,296,MAR,362.4400,0,0.637082,0.22,0.358374,0.36,0.135965,0.28,0.107446,0.54,0.35
41,39,256,JCI,138.2150,0,0.772542,0.36,0.285499,0.22,0.236431,0.66,0.042660,0.14,0.345
42,43,161,EQIX,1048.8100,0,0.369786,0.04,0.298609,0.26,0.320517,0.74,0.074236,0.32,0.34
43,38,343,NTRS,156.4500,0,0.786468,0.4,0.227160,0.1,0.082748,0.16,0.144090,0.7,0.34
44,45,187,FLS,79.2600,1,0.891617,0.48,0.556194,0.6,0.058151,0.08,0.058433,0.2,0.34
45,32,230,HST,20.5350,3,0.574794,0.18,0.293006,0.24,0.140183,0.32,0.105007,0.5,0.31
46,35,476,WAB,259.0550,0,0.503625,0.14,0.325953,0.32,0.144659,0.36,0.089419,0.38,0.3
47,46,167,ETR,115.0500,0,0.431647,0.08,0.206287,0.08,0.217051,0.6,0.084850,0.36,0.28
48,42,449,TXN,214.9900,0,0.470705,0.12,0.256691,0.18,0.119953,0.24,0.106968,0.52,0.265
49,49,64,BK,131.0750,0,0.726973,0.3,0.235602,0.12,0.057033,0.04,0.129134,0.6,0.265

## Calculating the Number of Shares to Buy

We'll use the `portfolio_input` function that we created earlier to accept our portfolio size. Then we will use similar logic in a `for` loop to calculate the number of shares to buy for each stock in our investment universe.

In [40]:
portfolio_input()

In [44]:
hqm_dataframe['Number of Shares to Buy'] = 0.0

portfolio_size = float(input('Enter the size of your portfolio: '))
position_size = portfolio_size / len(hqm_dataframe.index)

for i in range(0, len(hqm_dataframe)):
    hqm_dataframe.loc[i, 'Number of Shares to Buy'] = math.floor(
        position_size / hqm_dataframe.loc[i, 'Price']
    )

hqm_dataframe

,level_0,index,Ticker,Price,Number of Shares to Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile,HQM Score
0,0,422,STX,513.3500,0.0,6.163813,0.98,1.439244,0.98,0.648734,0.96,0.222700,0.92,0.96
1,1,202,GLW,168.3016,1.0,3.109083,0.94,1.001301,0.92,0.870684,1.0,0.296790,0.96,0.955
2,2,479,WDC,360.0900,0.0,9.080735,1.0,2.182192,1.0,0.673080,0.98,0.145725,0.72,0.925
3,3,242,INTC,65.3300,3.0,2.216741,0.88,0.833623,0.82,0.340969,0.76,0.482796,1.0,0.865
4,4,288,LRCX,264.0300,0.0,2.921391,0.92,0.915421,0.86,0.266759,0.7,0.166468,0.78,0.815
5,5,263,KEYS,325.4900,0.0,1.386465,0.72,0.974581,0.9,0.554394,0.92,0.132612,0.64,0.795
6,7,194,FTI,72.0100,2.0,1.849814,0.86,1.002802,0.94,0.378187,0.84,0.101010,0.44,0.77
7,6,266,KLAC,1725.3900,0.0,1.596550,0.78,0.688259,0.76,0.205133,0.56,0.165504,0.76,0.715
8,8,29,AMAT,387.4200,0.0,1.704530,0.82,0.781308,0.8,0.284916,0.72,0.099189,0.42,0.69
9,47,324,MU,452.4700,0.0,5.381897,0.96,1.419185,0.96,0.356982,0.8,-0.020230,0.02,0.685
10,12,246,IPGP,124.7200,1.0,1.288440,0.7,0.499039,0.56,0.608460,0.94,0.079827,0.34,0.635
11,15,23,ALB,187.9450,1.0,2.332362,0.9,0.963625,0.88,0.061169,0.12,0.130020,0.62,0.63
12,9,179,FCX,68.7900,2.0,1.068530,0.56,0.650564,0.74,0.143771,0.34,0.185316,0.86,0.625
13,20,42,APA,36.8900,5.0,1.552023,0.76,0.643480,0.7,0.395101,0.86,0.028283,0.08,0.6
14,11,79,CAT,774.0700,0.0,1.631560,0.8,0.474798,0.52,0.214377,0.58,0.102382,0.48,0.595
15,10,75,C,131.3500,1.0,1.131513,0.62,0.330246,0.34,0.174491,0.52,0.219385,0.88,0.59
16,14,31,AMD,256.6700,0.0,1.715979,0.84,0.176854,0.06,0.147853,0.38,0.307422,0.98,0.565
17,19,50,AVGO,394.2800,0.0,1.227451,0.68,0.149790,0.04,0.161910,0.46,0.229099,0.94,0.53
18,23,141,DOW,39.3850,5.0,0.456407,0.1,0.845519,0.84,0.410531,0.88,0.067326,0.26,0.52
19,17,87,CE,64.4760,3.0,0.649277,0.28,0.581508,0.64,0.373786,0.82,0.071386,0.3,0.51
20,13,10,ADI,345.5950,0.0,0.964545,0.52,0.477917,0.54,0.163385,0.48,0.101814,0.46,0.5
21,26,37,ANET,152.6900,1.0,1.073753,0.58,0.099557,0.02,0.219982,0.62,0.146821,0.74,0.49
22,29,385,PWR,587.9600,0.0,1.145512,0.64,0.362874,0.4,0.345466,0.78,0.028730,0.1,0.48
23,48,468,VLO,234.3400,0.0,1.189087,0.66,0.464631,0.5,0.265669,0.68,-0.005658,0.04,0.47
24,21,212,HAL,37.7150,5.0,0.825899,0.46,0.701837,0.78,0.148546,0.4,0.059624,0.22,0.465
25,16,412,SLB,52.5950,3.0,0.599628,0.2,0.638897,0.68,0.127538,0.26,0.141340,0.68,0.455
26,40,292,LYB,73.8000,2.0,0.405559,0.06,0.649257,0.72,0.438506,0.9,0.037992,0.12,0.45
27,18,344,NUE,189.1100,1.0,0.733852,0.32,0.375844,0.44,0.102331,0.22,0.171770,0.8,0.445
28,22,255,JBHT,224.7900,0.0,0.649075,0.26,0.620420,0.66,0.094456,0.2,0.123326,0.58,0.425
29,27,351,ODFL,206.0350,0.0,0.337373,0.02,0.526226,0.58,0.188841,0.54,0.116955,0.56,0.425
30,30,318,MS,192.8800,1.0,0.812655,0.44,0.254351,0.16,0.071312,0.14,0.220364,0.9,0.41
31,41,466,VFC,19.4900,10.0,0.772882,0.38,0.362230,0.38,0.018546,0.02,0.176920,0.84,0.405
32,33,102,CMI,596.8350,0.0,1.106655,0.6,0.443447,0.46,0.059532,0.1,0.098570,0.4,0.39
33,25,90,CFG,64.9450,3.0,0.893425,0.5,0.275260,0.2,0.092383,0.18,0.138728,0.66,0.385
34,28,66,BKR,60.7900,3.0,0.640884,0.24,0.368044,0.42,0.221277,0.64,0.066842,0.24,0.385
35,36,441,TPR,150.8850,1.0,1.399963,0.74,0.305843,0.28,0.136063,0.3,0.053961,0.16,0.37
36,44,180,FDX,362.8699,0.0,0.760977,0.34,0.559107,0.62,0.160931,0.44,0.022218,0.06,0.365
37,34,233,HWM,253.6100,0.0,0.995040,0.54,0.315642,0.3,0.152374,0.42,0.055882,0.18,0.36
38,37,421,STT,141.5600,1.0,0.798171,0.42,0.242672,0.14,0.057531,0.06,0.172019,0.82,0.36
39,31,402,ROST,223.5000,0.0,0.572226,0.16,0.446740,0.48,0.168275,0.5,0.069052,0.28,0.355
40,24,296,MAR,362.4400,0.0,0.637082,0.22,0.358374,0.36,0.135965,0.28,0.107446,0.54,0.35
41,39,256,JCI,138.2150,1.0,0.772542,0.36,0.285499,0.22,0.236431,0.66,0.042660,0.14,0.345
42,43,161,EQIX,1048.8100,0.0,0.369786,0.04,0.298609,0.26,0.320517,0.74,0.074236,0.32,0.34
43,38,343,NTRS,156.4500,1.0,0.786468,0.4,0.227160,0.1,0.082748,0.16,0.144090,0.7,0.34
44,45,187,FLS,79.2600,2.0,0.891617,0.48,0.556194,0.6,0.058151,0.08,0.058433,0.2,0.34
45,32,230,HST,20.5350,9.0,0.574794,0.18,0.293006,0.24,0.140183,0.32,0.105007,0.5,0.31
46,35,476,WAB,259.0550,0.0,0.503625,0.14,0.325953,0.32,0.144659,0.36,0.089419,0.38,0.3
47,46,167,ETR,115.0500,1.0,0.431647,0.08,0.206287,0.08,0.217051,0.6,0.084850,0.36,0.28
48,42,449,TXN,214.9900,0.0,0.470705,0.12,0.256691,0.18,0.119953,0.24,0.106968,0.52,0.265
49,49,64,BK,131.0750,1.0,0.726973,0.3,0.235602,0.12,0.057033,0.04,0.129134,0.6,0.265

## Formatting Our Excel Output

We will be using the XlsxWriter library for Python to create nicely-formatted Excel files.

XlsxWriter is an excellent package and offers tons of customization. However, the tradeoff for this is that the library can seem very complicated to new users. Accordingly, this section will be fairly long because I want to do a good job of explaining how XlsxWriter works.

In [52]:
writer = pd.ExcelWriter('momentum_strategy.xlsx', engine='xlsxwriter')
hqm_dataframe.to_excel(writer, sheet_name = "Momentum Strategy", index = False)

## Creating the Formats We'll Need For Our .xlsx File

You'll recall from our first project that formats include colors, fonts, and also symbols like % and $. We'll need four main formats for our Excel document:

* String format for tickers
* \$XX.XX format for stock prices
* \$XX,XXX format for market capitalization
* Integer format for the number of shares to purchase

Since we already built our formats in the last section of this course, I've included them below for you. Run this code cell before proceeding.

In [53]:
background_color = '#0a0a23'
font_color = '#ffffff'

string_template = writer.book.add_format(
        {
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

dollar_template = writer.book.add_format(
        {
            'num_format':'$0.00',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

integer_template = writer.book.add_format(
        {
            'num_format':'0',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

percent_template = writer.book.add_format(
        {
            'num_format':'0.0%',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
   )

In [67]:
import os

output_path = os.path.expanduser('~/Downloads/momentum_strategy.xlsx')

writer = pd.ExcelWriter(output_path, engine='xlsxwriter')
hqm_dataframe.to_excel(writer, sheet_name='Momentum Strategy', index=False)

column_formats = {
    'A': ['Ticker', string_template], 
    'B': ['Price', dollar_template], 
    'C': ['Number of Shares to Buy', integer_template], 
    'D': ['One-Year Price Return', percent_template], 
    'E': ['One-Year Return Percentile', percent_template],
    'F': ['Six-Month Price Return', percent_template],
    'G': ['Six-Month Return Percentile', percent_template],
    'H': ['Three-Month Price Return', percent_template],
    'I': ['Three-Month Return Percentile', percent_template],
    'J': ['One-Month Price Return', percent_template],
    'K': ['One-Month Return Percentile', percent_template],
    'L': ['HQM Score', percent_template]
}

for column in column_formats.keys():
    writer.sheets['Momentum Strategy'].set_column(f'{column}:{column}', 20, column_formats[column][1])
    writer.sheets['Momentum Strategy'].write(f'{column}1', column_formats[column][0], string_template)

## Saving Our Excel Output

As before, saving our Excel output is very easy:

In [68]:
writer.close()
print(f"File saved to: {output_path}")

File saved to: /Users/favourstjohn/Downloads/momentum_strategy.xlsx