# Quantitative Value Strategy
"Value investing" means investing in the stocks that are cheapest relative to common measures of business value (like earnings or assets).

For this project, we're going to build an investing strategy that selects the 50 stocks with the best value metrics. From there, we will calculate recommended trades for an equal-weight portfolio of these 50 stocks.

## Library Imports
The first thing we need to do is import the open-source software libraries that we'll be using in this tutorial.

In [1]:
import numpy as np
import pandas as pd
import xlsxwriter
import requests
from scipy import stats
import math
import yfinance as yf

## Importing Our List of Stocks & API Token
As before, we'll need to import our list of stocks and our API token before proceeding. Make sure the .csv file is still in your working directory and import it with the following command:

In [2]:
stocks = pd.read_csv('sp_500_stocks.csv')

## Making Our First API Call
It's now time to make the first version of our value screener!

We'll start by building a simple value screener that ranks securities based on a single metric (the price-to-earnings ratio).

In [3]:
symbol = 'AAPL'
ticker = yf.Ticker(symbol)
data = ticker.info
data

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers exclusive original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 150000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 64,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'totalPay': 16759518,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kevan  Parekh',
   'age': 53,
   'title': 'Senior VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4034174,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sabih  Khan',
   'age': 58,
   'title': 'Senior VP & Chief Operating Officer',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5021905,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 58,
   'title': 'Senior Vice President of Retail & People',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5037867,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 61,
   'title': 'Senior VP of Government Affairs & Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2025,
   'totalPay': 5022482,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ben  Borders',
   'age': 44,
   'title': 'Principal Accounting Officer',
   'yearBorn': 1981,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Jennifer G. Newstead J.D.',
   'age': 54,
   'title': 'Senior VP & General Counsel',
   'yearBorn': 1971,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kristin Huguet Quayle',
   'title': 'Vice President of Worldwide Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 2,
 'boardRisk': 1,
 'compensationRisk': 7,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1775001600,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://investor.apple.com/',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 263.4,
 'open': 267.098,
 'dayLow': 266.72,
 'dayHigh': 270.35,
 'regularMarketPreviousClose': 263.4,
 'regularMarketOpen': 267.098,
 'regularMarketDayLow': 266.72,
 'regularMarketDayHigh': 270.35,
 'dividendRate': 1.04,
 'dividendYield': 0.39,
 'exDividendDate': 1770595200,
 'payoutRatio': 0.1304,
 'fiveYearAvgDividendYield': 0.51,
 'beta': 1.109,
 'trailingPE': 34.20886,
 'forwardPE': 29.025309,
 'volume': 18916855,
 'regularMarketVolume': 18918047,
 'averageVolume': 46769181,
 'averageVolume10days': 40099560,
 'averageDailyVolume10Day': 40099560,
 'bid': 269.73,
 'ask': 270.97,
 'bidSize': 2,
 'askSize': 4,
 'marketCap': 3972114415616,
 'nonDilutedMarketCap': 3867012276000,
 'fiftyTwoWeekLow': 189.81,
 'fiftyTwoWeekHigh': 288.62,
 'allTimeHigh': 288.62,
 'allTimeLow': 0.049107,
 'priceToSalesTrailing12Months': 9.118364,
 'fiftyDayAverage': 260.6896,
 'twoHundredDayAverage': 251.8297,
 'trailingAnnualDividendRate': 1.03,
 'trailingAnnualDividendYield': 0.0039104023,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3890614370304,
 'profitMargins': 0.27037,
 'floatShares': 14656035251,
 'sharesOutstanding': 14681140000,
 'sharesShort': 126771284,
 'sharesShortPriorMonth': 129553812,
 'sharesShortPreviousMonthDate': 1772150400,
 'dateShortInterest': 1774915200,
 'sharesPercentSharesOut': 0.0086,
 'heldPercentInsiders': 0.0164,
 'heldPercentInstitutions': 0.65292,
 'shortRatio': 3.11,
 'shortPercentOfFloat': 0.0086,
 'impliedSharesOutstanding': 14697926000,
 'bookValue': 5.998,
 'priceToBook': 45.056683,
 'lastFiscalYearEnd': 1758931200,
 'nextFiscalYearEnd': 1790467200,
 'mostRecentQuarter': 1766793600,
 'earningsQuarterlyGrowth': 0.159,
 'netIncomeToCommon': 117776998400,
 'trailingEps': 7.9,
 'forwardEps': 9.31084,
 'pegRatio': 2.3712,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 8.931,
 'enterpriseToEbitda': 25.445,
 '52WeekChange': 0.36363637,
 'SandP52WeekChange': 0.36506534,
 'lastDividendValue': 0.26,
 'lastDividendDate': 1770595200,
 'quoteType': 'EQUITY',
 'currentPrice': 270.25,
 'targetHighPrice': 350.0,
 'targetLowPrice': 205.0,
 'targetMeanPrice': 296.4555,
 'targetMedianPrice': 300.0,
 'recommendationMean': 1.89583,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 40,
 'totalCash': 66907000832,
 'totalCashPerShare': 4.557,
 'ebitda': 152901992448,
 'totalDebt': 90509000704,
 'quickRatio': 0.845,
 'currentRatio': 0.974,
 'totalRevenue': 435617005568,
 'debtToEquity': 102.63,
 'revenuePerShare': 29.305,
 'returnOnAssets': 0.24377,
 'returnOnEquity': 1.5202099,
 'grossProfits': 206157004800,
 'freeCashflow': 106312753152,
 'operatingCashflow': 135471996928,
 'earningsGrowth': 0.183,
 'revenueGrowth': 0.157,
 'grossMargins': 0.47325,
 'ebitdaMargins': 0.35099998,
 'operatingMargins': 0.35374,
 'financialCurrency': 'USD',
 'symbol': 'AAPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.9 - Buy',
 'cryptoTradeable': False,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 345479400000,
 'corporateActions': [],
 'regularMarketTime': 1776437367,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_24937',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'regularMarketChange': 6.850006,
 'regularMarketDayRange': '266.72 - 270.35',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 46769181,
 'fiftyTwoWeekLowChange': 80.44,
 'fiftyTwoWeekLowChangePercent': 0.42379224,
 'fiftyTwoWeekRange': '189.81 - 288.62',
 'fiftyTwoWeekHighChange': -18.369995,
 'fiftyTwoWeekHighChangePercent': -0.06364769,
 'fiftyTwoWeekChangePercent': 36.363636,
 'dividendDate': 1770854400,
 'earningsTimestamp': 1777579200,
 'earningsTimestampStart': 1777579200,
 'earningsTimestampEnd': 1777579200,
 'earningsCallTimestampStart': 1777582800,
 'earningsCallTimestampEnd': 1777582800,
 'isEarningsDateEstimate': False,
 'epsTrailingTwelveMonths': 7.9,
 'epsForward': 9.31084,
 'epsCurrentYear': 8.52422,
 'priceEpsCurrentYear': 31.70378,
 'fiftyDayAverageChange': 9.560394,
 'fiftyDayAverageChangePercent': 0.03667348,
 'twoHundredDayAverageChange': 18.420303,
 'twoHundredDayAverageChangePercent': 0.073145874,
 'marketState': 'REGULAR',
 'regularMarketChangePercent': 2.6006098,
 'regularMarketPrice': 270.25,
 'shortName': 'Apple Inc.',
 'longName': 'Apple Inc.',
 'displayName': 'Apple',
 'trailingPegRatio': 2.3712}

## Parsing Our API Call
This API call has the metric we need - the price-to-earnings ratio.

Here is an example of how to parse the metric from our API call:

In [4]:
price = data['currentPrice']
pe_ratio = data['trailingPE']

## Executing A Batch API Call & Building Our DataFrame

Just like in our first project, it's now time to execute several batch API calls and add the information we need to our DataFrame.

We'll start by running the following code cell, which contains some code we already built last time that we can re-use for this project. More specifically, it contains a function called chunks that we can use to divide our list of securities into groups of 100.

In [5]:
# Function sourced from 
# https://stackoverflow.com/questions/312443/how-do-you-split-a-list-into-evenly-sized-chunks
def chunks(lst, n):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i:i + n]   
        
symbol_groups = list(chunks(stocks['Ticker'], 100))
symbol_strings = []
for i in range(0, len(symbol_groups)):
    symbol_strings.append(','.join(symbol_groups[i]))
#     print(symbol_strings[i])

my_columns = ['Ticker', 'Price', 'Price-to-Earnings Ratio', 'Number of Shares to Buy']

Now we need to create a blank DataFrame and add our data to the data frame one-by-one.

In [8]:
final_dataframe = pd.DataFrame(columns=my_columns)

for symbol in stocks['Ticker']:
    try:
        ticker = yf.Ticker(symbol)
        data = ticker.info
        final_dataframe = pd.concat([final_dataframe, pd.Series([symbol,
                                                                  data.get('currentPrice') or data.get('regularMarketPrice'),
                                                                  data.get('trailingPE'),
                                                                  'N/A'
                                                                  ],
                                                                 index=my_columns).to_frame().T],
                                    ignore_index=True)
    except Exception as e:
        print(f"Skipping {symbol}: {e}")

final_dataframe

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ANSS"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CMA"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: COG"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: FRC"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HBI"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HES"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: IPG"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: JNPR"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: K"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: NLSN"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TWTR"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: WBA"}}}

    Ticker    Price Price-to-Earnings Ratio Number of Shares to Buy
0        A   121.11               26.735098                     N/A
1      AAL   13.345                    78.5                     N/A
2      AAP    58.15                51.46018                     N/A
3     AAPL  269.945               34.170254                     N/A
4     ABBV    211.5               89.618645                     N/A
..     ...      ...                     ...                     ...
500    YUM   162.36               29.254053                     N/A
501    ZBH    96.31               27.129578                     N/A
502   ZBRA    239.0               29.217604                     N/A
503   ZION    62.93               10.470881                     N/A
504    ZTS   121.96               20.259136                     N/A

[505 rows x 4 columns]

## Removing Glamour Stocks

The opposite of a "value stock" is a "glamour stock". 

Since the goal of this strategy is to identify the 50 best value stocks from our universe, our next step is to remove glamour stocks from the DataFrame.

We'll sort the DataFrame by the stocks' price-to-earnings ratio, and drop all stocks outside the top 50.

In [19]:
final_dataframe.sort_values('Price-to-Earnings Ratio', inplace = True)
final_dataframe = final_dataframe[final_dataframe['Price-to-Earnings Ratio'] > 0]
final_dataframe = final_dataframe[:50]
final_dataframe.reset_index(inplace = True)
final_dataframe.drop('index', axis=1, inplace = True)
final_dataframe

   Ticker    Price Price-to-Earnings Ratio Number of Shares to Buy
0   CMCSA   29.715                5.512987                     N/A
1     ALL   216.02                5.674284                     N/A
2     DXC   13.205                5.741304                     N/A
3     EIX    70.12                6.070996                     N/A
4      WU    9.415                6.194079                     N/A
5     KSS    14.76                6.201681                     N/A
6     LNC    36.93                6.334477                     N/A
7    CHTR   239.17                6.603258                     N/A
8     VNO    29.24                6.961905                     N/A
9     LEG   12.195                7.215976                     N/A
10    HPQ   19.975                7.566287                     N/A
11    HRB    32.48                7.588785                     N/A
12    UHS   181.47                7.859246                     N/A
13    SYF    78.16                8.422415                     N/A
14    APA   33.765                8.462406                     N/A
15      T   26.455                8.702303                     N/A
16    GIS    35.81                8.755501                     N/A
17    MKC    54.05                8.860656                     N/A
18    TRV   304.04                9.075821                     N/A
19   PYPL   51.015                 9.42976                     N/A
20    DVN  42.1401               10.105539                     N/A
21   FISV    64.22               10.129337                     N/A
22    PRU   101.86               10.196197                     N/A
23    UAL   105.07               10.300735                     N/A
24    WHR    58.65               10.362191                     N/A
25    PGR   205.14               10.434384                     N/A
26   ZION    62.93               10.470881                     N/A
27    HIG   139.92               10.504504                     N/A
28   TROW    97.56               10.558441                     N/A
29     GL   151.17               10.744137                     N/A
30    BIO   300.44               10.783919                     N/A
31    DAL    74.66               10.899271                     N/A
32   CINF   166.29               10.954545                     N/A
33    AES    14.46               11.038169                     N/A
34     VZ    46.49                11.45074                     N/A
35    PHM  127.955               11.506745                     N/A
36    CPB    21.42               11.641304                     N/A
37    USB    56.66               11.878407                     N/A
38   HBAN   16.905               12.161871                     N/A
39     RF   28.195               12.258696                     N/A
40    MTB   220.21               12.364403                     N/A
41     CF   111.04               12.379041                     N/A
42     CI   276.65               12.467327                     N/A
43    WFC     81.9               12.658424                     N/A
44    AMP  464.035               12.797436                     N/A
45     CB   329.56               12.833333                     N/A
46    BBY   65.437               12.983531                     N/A
47    PNC   223.75               13.001163                     N/A
48    TFC    50.22               13.146598                     N/A
49    CCL    29.89                 13.1674                     N/A

## Calculating the Number of Shares to Buy
We now need to calculate the number of shares we need to buy. 

To do this, we will use the `portfolio_input` function that we created in our momentum project.

I have included this function below.

In [20]:
def portfolio_input():
    global portfolio_size
    portfolio_size = input("Enter the value of your portfolio:")

    try:
        val = float(portfolio_size)
    except ValueError:
        print("That's not a number! \n Try again:")
        portfolio_size = input("Enter the value of your portfolio:")

Use the `portfolio_input` function to accept a `portfolio_size` variable from the user of this script.

In [21]:
portfolio_input()

You can now use the global `portfolio_size` variable to calculate the number of shares that our strategy should purchase.

In [24]:
position_size = float(portfolio_size) / len(final_dataframe.index)

for i in range(0, len(final_dataframe['Ticker'])):
    final_dataframe.loc[i, 'Number of Shares to Buy'] = math.floor(position_size / final_dataframe['Price'][i])
final_dataframe

   Ticker    Price Price-to-Earnings Ratio Number of Shares to Buy
0   CMCSA   29.715                5.512987                     673
1     ALL   216.02                5.674284                      92
2     DXC   13.205                5.741304                    1514
3     EIX    70.12                6.070996                     285
4      WU    9.415                6.194079                    2124
5     KSS    14.76                6.201681                    1355
6     LNC    36.93                6.334477                     541
7    CHTR   239.17                6.603258                      83
8     VNO    29.24                6.961905                     683
9     LEG   12.195                7.215976                    1640
10    HPQ   19.975                7.566287                    1001
11    HRB    32.48                7.588785                     615
12    UHS   181.47                7.859246                     110
13    SYF    78.16                8.422415                     255
14    APA   33.765                8.462406                     592
15      T   26.455                8.702303                     756
16    GIS    35.81                8.755501                     558
17    MKC    54.05                8.860656                     370
18    TRV   304.04                9.075821                      65
19   PYPL   51.015                 9.42976                     392
20    DVN  42.1401               10.105539                     474
21   FISV    64.22               10.129337                     311
22    PRU   101.86               10.196197                     196
23    UAL   105.07               10.300735                     190
24    WHR    58.65               10.362191                     341
25    PGR   205.14               10.434384                      97
26   ZION    62.93               10.470881                     317
27    HIG   139.92               10.504504                     142
28   TROW    97.56               10.558441                     205
29     GL   151.17               10.744137                     132
30    BIO   300.44               10.783919                      66
31    DAL    74.66               10.899271                     267
32   CINF   166.29               10.954545                     120
33    AES    14.46               11.038169                    1383
34     VZ    46.49                11.45074                     430
35    PHM  127.955               11.506745                     156
36    CPB    21.42               11.641304                     933
37    USB    56.66               11.878407                     352
38   HBAN   16.905               12.161871                    1183
39     RF   28.195               12.258696                     709
40    MTB   220.21               12.364403                      90
41     CF   111.04               12.379041                     180
42     CI   276.65               12.467327                      72
43    WFC     81.9               12.658424                     244
44    AMP  464.035               12.797436                      43
45     CB   329.56               12.833333                      60
46    BBY   65.437               12.983531                     305
47    PNC   223.75               13.001163                      89
48    TFC    50.22               13.146598                     398
49    CCL    29.89                 13.1674                     669

## Building a Better (and More Realistic) Value Strategy
Every valuation metric has certain flaws.

For example, the price-to-earnings ratio doesn't work well with stocks with negative earnings.

Similarly, stocks that buyback their own shares are difficult to value using the price-to-book ratio.

Investors typically use a `composite` basket of valuation metrics to build robust quantitative value strategies. In this section, we will filter for stocks with the lowest percentiles on the following metrics:

* Price-to-earnings ratio
* Price-to-book ratio
* Price-to-sales ratio
* Enterprise Value divided by Earnings Before Interest, Taxes, Depreciation, and Amortization (EV/EBITDA)
* Enterprise Value divided by Gross Profit (EV/GP)

Some of these metrics aren't provided directly by the IEX Cloud API, and must be computed after pulling raw data. We'll start by calculating each data point from scratch.

In [25]:
symbol = 'AAPL'
ticker = yf.Ticker(symbol)
data = ticker.info

# P/E Ratio
pe_ratio = data['trailingPE']
# P/B Ratio
pb_ratio = data['priceToBook']
# P/S Ratio
ps_ratio = data['priceToSalesTrailing12Months']
# EV/EBITDA
enterprise_value = data['enterpriseValue']
ebitda = data['ebitda']
ev_to_ebitda = enterprise_value / ebitda
# EV/GP
gross_profit = data['grossProfits']
ev_to_gross_profit = enterprise_value / gross_profit

Let's move on to building our DataFrame. You'll notice that I use the abbreviation `rv` often. It stands for `robust value`, which is what we'll call this sophisticated strategy moving forward.

In [26]:
rv_columns = [
    'Ticker',
    'Price',
    'Number of Shares to Buy',
    'Price-to-Earnings Ratio',
    'PE Percentile',
    'Price-to-Book Ratio',
    'PB Percentile',
    'Price-to-Sales Ratio',
    'PS Percentile',
    'EV/EBITDA',
    'EV/EBITDA Percentile',
    'EV/GP',
    'EV/GP Percentile',
    'RV Score'
]

rv_dataframe = pd.DataFrame(columns=rv_columns)

for symbol in stocks['Ticker']:
    try:
        ticker = yf.Ticker(symbol)
        data = ticker.info

        enterprise_value = data.get('enterpriseValue')
        ebitda = data.get('ebitda')
        gross_profit = data.get('grossProfits')

        try:
            ev_to_ebitda = enterprise_value / ebitda
        except TypeError:
            ev_to_ebitda = np.NaN

        try:
            ev_to_gross_profit = enterprise_value / gross_profit
        except TypeError:
            ev_to_gross_profit = np.NaN

        rv_dataframe = pd.concat([rv_dataframe, pd.Series([
                symbol,
                data.get('currentPrice') or data.get('regularMarketPrice'),
                'N/A',
                data.get('trailingPE'),
                'N/A',
                data.get('priceToBook'),
                'N/A',
                data.get('priceToSalesTrailing12Months'),
                'N/A',
                ev_to_ebitda,
                'N/A',
                ev_to_gross_profit,
                'N/A',
                'N/A'
        ], index=rv_columns).to_frame().T], ignore_index=True)

    except Exception as e:
        print(f"Skipping {symbol}: {e}")

rv_dataframe

Skipping ABC: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping ABMD: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping ABT: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping ALXN: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping AMP: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ANSS"}}}

Skipping ANSS: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping ANTM: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping ATVI: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping AXP: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping BAC: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping BF.B: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping BK: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping BLL: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping BRK.B: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping C: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping CERN: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping CFG: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CMA"}}}

Skipping CMA: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping COF: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping COG: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping CTL: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping CTXS: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping CXO: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping DFS: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping DISCA: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping DISCK: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping DISH: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping DRE: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping ETFC: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping FB: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping FBHS: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping FISV: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping FITB: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping FLIR: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping FLT: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping FRC: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping GPS: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping GS: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping HBAN: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HBI"}}}

Skipping HBI: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HES"}}}

Skipping HES: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping HFC: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping INFO: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: IPG"}}}

Skipping IPG: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping JNPR: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping JPM: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: K"}}}

Skipping K: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping KEY: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping KSU: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping MMC: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping MRO: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping MS: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping MTB: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping MXIM: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping MYL: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping NBL: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping NLOK: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping NLSN: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping NTRS: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping PBCT: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping PEAK: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping PKI: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping PNC: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping PXD: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping RE: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping RF: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping RJF: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping SCHW: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping SIVB: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping STT: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping SYF: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping TFC: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping TIF: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping TWTR: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping USB: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping VAR: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping VIAC: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: WBA"}}}

Skipping WBA: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping WFC: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping WLTW: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping WRK: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping XLNX: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Skipping ZION: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

,Ticker,Price,Number of Shares to Buy,Price-to-Earnings Ratio,PE Percentile,Price-to-Book Ratio,PB Percentile,Price-to-Sales Ratio,PS Percentile,EV/EBITDA,EV/EBITDA Percentile,EV/GP,EV/GP Percentile,RV Score
0,A,121.17,N/A,26.748343,N/A,4.958667,N/A,None,N/A,17.863888,N/A,9.529018,N/A,N/A
1,AAL,13.155,N/A,77.38235,N/A,-2.330794,N/A,0.158994,N/A,9.863492,N/A,3.100953,N/A,N/A
2,AAP,57.935,N/A,51.269913,N/A,1.581498,N/A,0.406368,N/A,12.560816,N/A,1.57468,N/A,N/A
3,AAPL,271.37,N/A,34.3519,N/A,45.245083,N/A,9.156153,N/A,25.445152,N/A,18.872094,N/A,N/A
4,ABBV,211.25,N/A,89.51272,N/A,-114.189186,N/A,6.109402,N/A,14.79164,N/A,9.878653,N/A,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
417,XYL,122.11,N/A,31.150509,N/A,2.590919,N/A,3.286109,N/A,16.741677,N/A,9.124816,N/A,N/A
418,YUM,162.065,N/A,29.200901,N/A,-6.128612,N/A,5.45406,N/A,19.44197,N/A,14.919867,N/A,N/A
419,ZBH,95.985,N/A,27.038029,N/A,1.477829,N/A,2.281438,N/A,10.341026,N/A,4.497211,N/A,N/A
420,ZBRA,237.23,N/A,29.00122,N/A,3.278967,N/A,2.162667,N/A,14.249376,N/A,5.412895,N/A,N/A
421,ZTS,122.155,N/A,20.291529,N/A,15.582982,N/A,5.446816,N/A,14.080444,N/A,8.411854,N/A,N/A

## Dealing With Missing Data in Our DataFrame

Our DataFrame contains some missing data because all of the metrics we require are not available through the API we're using. 

You can use pandas' `isnull` method to identify missing data:

In [29]:
rv_dataframe[rv_dataframe.isnull().any(axis=1)]

,Ticker,Price,Number of Shares to Buy,Price-to-Earnings Ratio,PE Percentile,Price-to-Book Ratio,PB Percentile,Price-to-Sales Ratio,PS Percentile,EV/EBITDA,EV/EBITDA Percentile,EV/GP,EV/GP Percentile,RV Score
0,A,121.17,N/A,26.748343,N/A,4.958667,N/A,None,N/A,17.863888,N/A,9.529018,N/A,N/A
20,ALB,196.21,N/A,None,N/A,3.164729,N/A,4.497723,N/A,40.115954,N/A,43.943274,N/A,N/A
36,APD,292.0,N/A,None,N/A,4.218678,N/A,5.32552,N/A,100.927831,N/A,22.21233,N/A,N/A
39,ARE,48.715,N/A,None,N/A,0.537023,N/A,2.798322,N/A,12.481583,N/A,11.558957,N/A,N/A
47,BAX,18.775,N/A,None,N/A,1.575348,N/A,0.862028,N/A,8.483573,N/A,4.260789,N/A,N/A
61,CAG,14.8497,N/A,None,N/A,0.870236,N/A,0.635405,N/A,8.274734,N/A,5.272198,N/A,N/A
72,CE,62.345,N/A,None,N/A,1.687143,N/A,0.731122,N/A,12.528565,N/A,9.975623,N/A,N/A
86,CNC,38.705,N/A,None,N/A,0.953913,N/A,0.108055,N/A,6.686478,N/A,0.928184,N/A,N/A
91,COTY,2.415,N/A,None,N/A,0.600896,N/A,0.365956,N/A,6.559427,N/A,1.427104,N/A,N/A
114,DOW,35.27,N/A,None,N/A,1.580268,N/A,0.635032,N/A,16.829433,N/A,18.261725,N/A,N/A
129,EL,77.8,N/A,None,N/A,6.978288,N/A,1.918231,N/A,15.220188,N/A,3.078099,N/A,N/A
145,F,12.97,N/A,None,N/A,1.439033,N/A,0.277805,N/A,34.667545,N/A,17.184014,N/A,N/A
154,FMC,17.26,N/A,None,N/A,1.04095,N/A,0.622448,N/A,14.108363,N/A,4.979988,N/A,N/A
175,HAS,97.2575,N/A,None,N/A,25.353884,N/A,2.910417,N/A,13.061175,N/A,5.224209,N/A,N/A
183,HPE,26.145,N/A,None,N/A,1.402478,N/A,0.971986,N/A,10.476943,N/A,4.469358,N/A,N/A
196,IFF,75.49,N/A,None,N/A,1.363768,N/A,1.770982,N/A,13.187679,N/A,6.22212,N/A,N/A
199,INTC,70.115,N/A,None,N/A,3.064368,N/A,6.660892,N/A,28.807845,N/A,18.832057,N/A,N/A
201,IP,37.43,N/A,None,N/A,1.333025,N/A,0.838566,N/A,7.232649,N/A,4.062962,N/A,N/A
209,IVZ,24.855,N/A,None,N/A,1.135294,N/A,1.73173,N/A,11.821334,N/A,8.304323,N/A,N/A
216,KHC,22.615,N/A,None,N/A,0.642672,N/A,1.073306,N/A,7.851021,N/A,5.410685,N/A,N/A
243,LYB,67.215,N/A,None,N/A,2.147307,N/A,0.719495,N/A,16.361715,N/A,13.189855,N/A,N/A
244,LYV,157.655,N/A,None,N/A,136.14421,N/A,1.468874,N/A,21.48431,N/A,6.550748,N/A,N/A
250,MCHP,79.12,N/A,None,N/A,6.526437,N/A,9.792023,N/A,47.709951,N/A,19.297855,N/A,N/A
288,NWL,4.45,N/A,None,N/A,0.780154,N/A,0.262483,N/A,8.752941,N/A,2.870936,N/A,N/A
294,OMC,79.84,N/A,None,N/A,2.075222,N/A,1.434541,N/A,10.68263,N/A,9.30313,N/A,N/A
317,PRGO,11.66,N/A,None,N/A,0.546545,N/A,0.37737,N/A,7.195168,N/A,3.272369,N/A,N/A
342,SJM,95.9,N/A,None,N/A,1.954192,N/A,1.146235,N/A,9.293339,N/A,5.718791,N/A,N/A
344,SLG,42.81,N/A,None,N/A,0.88319,N/A,3.463774,N/A,26.28854,N/A,20.768819,N/A,N/A
359,TAP,44.43,N/A,None,N/A,0.828919,N/A,0.75089,N/A,5.985446,N/A,3.309176,N/A,N/A
374,TTWO,216.23,N/A,None,N/A,11.449827,N/A,6.104571,N/A,49.534491,N/A,10.483153,N/A,N/A
378,UA,6.3799,N/A,None,N/A,1.893145,N/A,0.546071,N/A,39.427637,N/A,1.645357,N/A,N/A
379,UAA,6.5781,N/A,None,N/A,1.951958,N/A,0.563035,N/A,40.220267,N/A,1.678435,N/A,N/A
415,XRAY,12.665,N/A,None,N/A,1.888044,N/A,0.687453,N/A,7.606314,N/A,2.467918,N/A,N/A
416,XRX,1.725,N/A,None,N/A,0.497405,N/A,0.032126,N/A,15.431762,N/A,2.249663,N/A,N/A

Dealing with missing data is an important topic in data science.

There are two main approaches:

* Drop missing data from the data set (pandas' `dropna` method is useful here)
* Replace missing data with a new value (pandas' `fillna` method is useful here)

In this tutorial, we will replace missing data with the average non-`NaN` data point from that column. 

Here is the code to do this:

In [30]:
for column in ['Price-to-Earnings Ratio', 'Price-to-Book Ratio','Price-to-Sales Ratio',  'EV/EBITDA','EV/GP']:
    rv_dataframe[column].fillna(rv_dataframe[column].mean(), inplace = True)

/var/folders/5w/xpk6g_79155419v0g1n09y4c0000gn/T/ipykernel_44876/2238724823.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  rv_dataframe[column].fillna(rv_dataframe[column].mean(), inplace = True)

Now, if we run the statement from earlier to print rows that contain missing data, nothing should be returned:

In [31]:
rv_dataframe[rv_dataframe.isnull().any(axis=1)]

,Ticker,Price,Number of Shares to Buy,Price-to-Earnings Ratio,PE Percentile,Price-to-Book Ratio,PB Percentile,Price-to-Sales Ratio,PS Percentile,EV/EBITDA,EV/EBITDA Percentile,EV/GP,EV/GP Percentile,RV Score
0,A,121.17,N/A,26.748343,N/A,4.958667,N/A,None,N/A,17.863888,N/A,9.529018,N/A,N/A
20,ALB,196.21,N/A,None,N/A,3.164729,N/A,4.497723,N/A,40.115954,N/A,43.943274,N/A,N/A
36,APD,292.0,N/A,None,N/A,4.218678,N/A,5.32552,N/A,100.927831,N/A,22.21233,N/A,N/A
39,ARE,48.715,N/A,None,N/A,0.537023,N/A,2.798322,N/A,12.481583,N/A,11.558957,N/A,N/A
47,BAX,18.775,N/A,None,N/A,1.575348,N/A,0.862028,N/A,8.483573,N/A,4.260789,N/A,N/A
61,CAG,14.8497,N/A,None,N/A,0.870236,N/A,0.635405,N/A,8.274734,N/A,5.272198,N/A,N/A
72,CE,62.345,N/A,None,N/A,1.687143,N/A,0.731122,N/A,12.528565,N/A,9.975623,N/A,N/A
86,CNC,38.705,N/A,None,N/A,0.953913,N/A,0.108055,N/A,6.686478,N/A,0.928184,N/A,N/A
91,COTY,2.415,N/A,None,N/A,0.600896,N/A,0.365956,N/A,6.559427,N/A,1.427104,N/A,N/A
114,DOW,35.27,N/A,None,N/A,1.580268,N/A,0.635032,N/A,16.829433,N/A,18.261725,N/A,N/A
129,EL,77.8,N/A,None,N/A,6.978288,N/A,1.918231,N/A,15.220188,N/A,3.078099,N/A,N/A
145,F,12.97,N/A,None,N/A,1.439033,N/A,0.277805,N/A,34.667545,N/A,17.184014,N/A,N/A
154,FMC,17.26,N/A,None,N/A,1.04095,N/A,0.622448,N/A,14.108363,N/A,4.979988,N/A,N/A
175,HAS,97.2575,N/A,None,N/A,25.353884,N/A,2.910417,N/A,13.061175,N/A,5.224209,N/A,N/A
183,HPE,26.145,N/A,None,N/A,1.402478,N/A,0.971986,N/A,10.476943,N/A,4.469358,N/A,N/A
196,IFF,75.49,N/A,None,N/A,1.363768,N/A,1.770982,N/A,13.187679,N/A,6.22212,N/A,N/A
199,INTC,70.115,N/A,None,N/A,3.064368,N/A,6.660892,N/A,28.807845,N/A,18.832057,N/A,N/A
201,IP,37.43,N/A,None,N/A,1.333025,N/A,0.838566,N/A,7.232649,N/A,4.062962,N/A,N/A
209,IVZ,24.855,N/A,None,N/A,1.135294,N/A,1.73173,N/A,11.821334,N/A,8.304323,N/A,N/A
216,KHC,22.615,N/A,None,N/A,0.642672,N/A,1.073306,N/A,7.851021,N/A,5.410685,N/A,N/A
243,LYB,67.215,N/A,None,N/A,2.147307,N/A,0.719495,N/A,16.361715,N/A,13.189855,N/A,N/A
244,LYV,157.655,N/A,None,N/A,136.14421,N/A,1.468874,N/A,21.48431,N/A,6.550748,N/A,N/A
250,MCHP,79.12,N/A,None,N/A,6.526437,N/A,9.792023,N/A,47.709951,N/A,19.297855,N/A,N/A
288,NWL,4.45,N/A,None,N/A,0.780154,N/A,0.262483,N/A,8.752941,N/A,2.870936,N/A,N/A
294,OMC,79.84,N/A,None,N/A,2.075222,N/A,1.434541,N/A,10.68263,N/A,9.30313,N/A,N/A
317,PRGO,11.66,N/A,None,N/A,0.546545,N/A,0.37737,N/A,7.195168,N/A,3.272369,N/A,N/A
342,SJM,95.9,N/A,None,N/A,1.954192,N/A,1.146235,N/A,9.293339,N/A,5.718791,N/A,N/A
344,SLG,42.81,N/A,None,N/A,0.88319,N/A,3.463774,N/A,26.28854,N/A,20.768819,N/A,N/A
359,TAP,44.43,N/A,None,N/A,0.828919,N/A,0.75089,N/A,5.985446,N/A,3.309176,N/A,N/A
374,TTWO,216.23,N/A,None,N/A,11.449827,N/A,6.104571,N/A,49.534491,N/A,10.483153,N/A,N/A
378,UA,6.3799,N/A,None,N/A,1.893145,N/A,0.546071,N/A,39.427637,N/A,1.645357,N/A,N/A
379,UAA,6.5781,N/A,None,N/A,1.951958,N/A,0.563035,N/A,40.220267,N/A,1.678435,N/A,N/A
415,XRAY,12.665,N/A,None,N/A,1.888044,N/A,0.687453,N/A,7.606314,N/A,2.467918,N/A,N/A
416,XRX,1.725,N/A,None,N/A,0.497405,N/A,0.032126,N/A,15.431762,N/A,2.249663,N/A,N/A

## Calculating Value Percentiles

We now need to calculate value score percentiles for every stock in the universe. More specifically, we need to calculate percentile scores for the following metrics for every stock:

* Price-to-earnings ratio
* Price-to-book ratio
* Price-to-sales ratio
* EV/EBITDA
* EV/GP

Here's how we'll do this:

In [33]:
metrics = {
    'Price-to-Earnings Ratio': 'PE Percentile',
    'Price-to-Book Ratio': 'PB Percentile',
    'Price-to-Sales Ratio': 'PS Percentile',
    'EV/EBITDA': 'EV/EBITDA Percentile',
    'EV/GP': 'EV/GP Percentile'
}

for metric in metrics.keys():
    rv_dataframe[metric] = pd.to_numeric(rv_dataframe[metric], errors='coerce')

for row in rv_dataframe.index:
    for metric in metrics.keys():
        rv_dataframe.loc[row, metrics[metric]] = stats.percentileofscore(rv_dataframe[metric].dropna(), rv_dataframe.loc[row, metric]) / 100

for metric in metrics.values():
    print(rv_dataframe[metric])

rv_dataframe

0       0.51928
1      0.953728
2       0.88946
3      0.727506
4      0.969152
         ...
417    0.627249
418    0.575835
419    0.524422
420    0.573265
421    0.282776
Name: PE Percentile, Length: 422, dtype: object
0      0.656398
1       0.07346
2        0.2109
3      0.983412
4      0.007109
         ...
417    0.440758
418    0.061611
419    0.191943
420    0.526066
421    0.898104
Name: PB Percentile, Length: 422, dtype: object
0           NaN
1      0.009501
2      0.054632
3      0.895487
4      0.769596
         ...
417    0.541568
418    0.731591
419    0.415677
420    0.396675
421    0.726841
Name: PS Percentile, Length: 422, dtype: object
0       0.64455
1      0.206161
2      0.353081
3       0.86019
4      0.495261
         ...
417    0.597156
418    0.720379
419    0.234597
420    0.450237
421    0.440758
Name: EV/EBITDA Percentile, Length: 422, dtype: object
0      0.547393
1      0.078199
2      0.018957
3      0.902844
4      0.563981
         ...
417    0.523697
418    0.774882
419    0.187204
420    0.260664
421    0.478673
Name: EV/GP Percentile, Length: 422, dtype: object

,Ticker,Price,Number of Shares to Buy,Price-to-Earnings Ratio,PE Percentile,Price-to-Book Ratio,PB Percentile,Price-to-Sales Ratio,PS Percentile,EV/EBITDA,EV/EBITDA Percentile,EV/GP,EV/GP Percentile,RV Score
0,A,121.17,N/A,26.748343,0.51928,4.958667,0.656398,NaN,NaN,17.863888,0.64455,9.529018,0.547393,N/A
1,AAL,13.155,N/A,77.382350,0.953728,-2.330794,0.07346,0.158994,0.009501,9.863492,0.206161,3.100953,0.078199,N/A
2,AAP,57.935,N/A,51.269913,0.88946,1.581498,0.2109,0.406368,0.054632,12.560816,0.353081,1.574680,0.018957,N/A
3,AAPL,271.37,N/A,34.351900,0.727506,45.245083,0.983412,9.156153,0.895487,25.445152,0.86019,18.872094,0.902844,N/A
4,ABBV,211.25,N/A,89.512720,0.969152,-114.189186,0.007109,6.109402,0.769596,14.791640,0.495261,9.878653,0.563981,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
417,XYL,122.11,N/A,31.150509,0.627249,2.590919,0.440758,3.286109,0.541568,16.741677,0.597156,9.124816,0.523697,N/A
418,YUM,162.065,N/A,29.200901,0.575835,-6.128612,0.061611,5.454060,0.731591,19.441970,0.720379,14.919867,0.774882,N/A
419,ZBH,95.985,N/A,27.038029,0.524422,1.477829,0.191943,2.281438,0.415677,10.341026,0.234597,4.497211,0.187204,N/A
420,ZBRA,237.23,N/A,29.001220,0.573265,3.278967,0.526066,2.162667,0.396675,14.249376,0.450237,5.412895,0.260664,N/A
421,ZTS,122.155,N/A,20.291529,0.282776,15.582982,0.898104,5.446816,0.726841,14.080444,0.440758,8.411854,0.478673,N/A

## Calculating the RV Score
We'll now calculate our RV Score (which stands for Robust Value), which is the value score that we'll use to filter for stocks in this investing strategy.

The RV Score will be the arithmetic mean of the 4 percentile scores that we calculated in the last section.

To calculate arithmetic mean, we will use the mean function from Python's built-in statistics module.

In [34]:
from statistics import mean

for row in rv_dataframe.index:
    value_percentiles = []
    for metric in metrics.keys():
        value_percentiles.append(rv_dataframe.loc[row, metrics[metric]])
    rv_dataframe.loc[row, 'RV Score'] = mean(value_percentiles)
    
rv_dataframe

,Ticker,Price,Number of Shares to Buy,Price-to-Earnings Ratio,PE Percentile,Price-to-Book Ratio,PB Percentile,Price-to-Sales Ratio,PS Percentile,EV/EBITDA,EV/EBITDA Percentile,EV/GP,EV/GP Percentile,RV Score
0,A,121.17,N/A,26.748343,0.51928,4.958667,0.656398,NaN,NaN,17.863888,0.64455,9.529018,0.547393,NaN
1,AAL,13.155,N/A,77.382350,0.953728,-2.330794,0.07346,0.158994,0.009501,9.863492,0.206161,3.100953,0.078199,0.26421
2,AAP,57.935,N/A,51.269913,0.88946,1.581498,0.2109,0.406368,0.054632,12.560816,0.353081,1.574680,0.018957,0.305406
3,AAPL,271.37,N/A,34.351900,0.727506,45.245083,0.983412,9.156153,0.895487,25.445152,0.86019,18.872094,0.902844,0.873888
4,ABBV,211.25,N/A,89.512720,0.969152,-114.189186,0.007109,6.109402,0.769596,14.791640,0.495261,9.878653,0.563981,0.56102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
417,XYL,122.11,N/A,31.150509,0.627249,2.590919,0.440758,3.286109,0.541568,16.741677,0.597156,9.124816,0.523697,0.546086
418,YUM,162.065,N/A,29.200901,0.575835,-6.128612,0.061611,5.454060,0.731591,19.441970,0.720379,14.919867,0.774882,0.57286
419,ZBH,95.985,N/A,27.038029,0.524422,1.477829,0.191943,2.281438,0.415677,10.341026,0.234597,4.497211,0.187204,0.310769
420,ZBRA,237.23,N/A,29.001220,0.573265,3.278967,0.526066,2.162667,0.396675,14.249376,0.450237,5.412895,0.260664,0.441381
421,ZTS,122.155,N/A,20.291529,0.282776,15.582982,0.898104,5.446816,0.726841,14.080444,0.440758,8.411854,0.478673,0.565431

## Selecting the 50 Best Value Stocks¶

As before, we can identify the 50 best value stocks in our universe by sorting the DataFrame on the RV Score column and dropping all but the top 50 entries.

In [35]:
rv_dataframe.sort_values(by = 'RV Score', inplace = True)
rv_dataframe = rv_dataframe[:50]
rv_dataframe.reset_index(drop = True, inplace = True)

## Calculating the Number of Shares to Buy
We'll use the `portfolio_input` function that we created earlier to accept our portfolio size. Then we will use similar logic in a for loop to calculate the number of shares to buy for each stock in our investment universe.

In [42]:
portfolio_input()

In [43]:
position_size = float(portfolio_size) / len(rv_dataframe.index)
for i in range(0, len(rv_dataframe['Ticker'])-1):
    rv_dataframe.loc[i, 'Number of Shares to Buy'] = math.floor(position_size / rv_dataframe['Price'][i])
rv_dataframe

,Ticker,Price,Number of Shares to Buy,Price-to-Earnings Ratio,PE Percentile,Price-to-Book Ratio,PB Percentile,Price-to-Sales Ratio,PS Percentile,EV/EBITDA,EV/EBITDA Percentile,EV/GP,EV/GP Percentile,RV Score
0,DXC,13.095,1,5.693479,0.007712,0.707991,0.094787,0.179791,0.011876,2.619777,0.007109,1.630122,0.021327,0.028562
1,KSS,14.6,1,6.134454,0.012853,0.403951,0.075829,0.105551,0.004751,6.251267,0.049763,1.200831,0.009479,0.030535
2,LNC,36.945,0,6.337050,0.017995,0.707813,0.092417,0.384416,0.049881,-24.963932,0.004739,-6.826296,0.00237,0.03348
3,HPQ,19.945,1,7.554924,0.028278,-23.886229,0.033175,0.325618,0.04038,5.792894,0.030806,2.267404,0.040284,0.034585
4,CMCSA,29.705,0,5.511132,0.002571,1.104850,0.132701,0.874986,0.171021,5.466968,0.023697,2.271641,0.045024,0.075003
5,UHS,181.83,0,7.874837,0.033419,1.526060,0.194313,0.639648,0.111639,6.154545,0.045024,2.109938,0.033175,0.083514
6,PRU,101.825,0,10.192693,0.051414,1.092215,0.127962,0.578693,0.090261,7.851124,0.123223,2.270836,0.042654,0.087103
7,LEG,12.1101,1,7.165739,0.025707,1.605475,0.218009,0.407352,0.057007,7.061988,0.07346,3.457796,0.104265,0.09569
8,HUM,201.8,0,20.508130,0.29563,1.378227,0.170616,0.187687,0.014252,4.947561,0.016588,0.936656,0.007109,0.100839
9,HRB,32.36,0,7.560748,0.030848,-4.983829,0.066351,1.082156,0.204276,6.902198,0.07109,3.963398,0.13981,0.102475
10,MHK,110.75,0,18.676224,0.244216,0.813435,0.101896,0.631106,0.099762,5.770052,0.028436,2.902656,0.07109,0.10908
11,LKQ,31.56,0,13.662337,0.11054,1.231129,0.154028,0.590023,0.092637,8.399825,0.146919,2.385136,0.047393,0.110304
12,ALL,215.925,0,5.671789,0.005141,1.962330,0.319905,0.827957,0.16152,4.769663,0.011848,2.813034,0.061611,0.112005
13,LEN,94.155,0,13.547482,0.107969,1.059910,0.123223,0.699030,0.130641,7.473999,0.099526,3.315299,0.099526,0.112177
14,WHR,58.025,0,10.251767,0.059126,1.191992,0.14218,0.240856,0.021378,9.489375,0.194313,4.124259,0.149289,0.113257
15,CHTR,240.6,0,6.642739,0.020566,1.897821,0.28673,0.556241,0.08076,6.022225,0.040284,4.384824,0.172986,0.120265
16,UAL,104.0599,0,10.201951,0.053985,2.202606,0.369668,0.571914,0.087886,6.387053,0.052133,2.468926,0.056872,0.124109
17,CI,277.035,0,12.484677,0.092545,1.749787,0.248815,0.269200,0.030879,7.945821,0.125592,3.745043,0.132701,0.126107
18,CPB,21.25,0,11.548913,0.087404,1.581101,0.208531,0.631226,0.102138,7.496959,0.101896,4.406860,0.175355,0.135065
19,APA,34.32,0,8.604011,0.03599,1.988762,0.322275,1.396512,0.249406,3.612948,0.009479,3.147491,0.082938,0.140018
20,MOS,24.23,0,14.250000,0.128535,0.636261,0.087678,0.638309,0.109264,5.758360,0.026066,6.837428,0.369668,0.144242
21,AIG,78.99,0,14.546962,0.138817,1.033346,0.118483,1.592681,0.287411,5.010063,0.018957,4.370974,0.170616,0.146857
22,L,110.79,0,13.900879,0.118252,1.221405,0.149289,1.237054,0.223278,8.071206,0.132701,3.901403,0.137441,0.152192
23,DVA,147.46,0,15.505784,0.156812,-15.525374,0.047393,0.722532,0.135392,8.679309,0.158768,5.426131,0.263033,0.15228
24,WU,9.435,2,6.207237,0.015424,3.109756,0.5,0.730108,0.137767,5.124496,0.021327,3.189274,0.087678,0.152439
25,TRV,303.5,0,9.059702,0.046272,2.006784,0.327014,1.318656,0.230404,6.198197,0.047393,4.073068,0.146919,0.159601
26,DVN,42.565,0,10.207434,0.056555,1.704987,0.241706,1.649348,0.301663,4.773144,0.014218,4.664578,0.194313,0.161691
27,BBY,64.73,0,12.843255,0.097686,4.566491,0.63981,0.325327,0.038005,6.059305,0.042654,1.682099,0.028436,0.169318
28,HIG,139.69,0,10.487238,0.064267,2.074737,0.336493,1.358026,0.239905,7.365705,0.092417,3.628071,0.118483,0.170313
29,T,26.45,0,8.700658,0.041131,1.684070,0.236967,1.473683,0.273159,7.777507,0.118483,4.598549,0.191943,0.172337
30,VZ,46.555,0,11.466749,0.082262,1.879491,0.277251,1.420891,0.261283,7.287443,0.085308,4.463381,0.180095,0.17724
31,PYPL,50.8,0,9.390018,0.048843,2.307308,0.398104,1.409917,0.256532,7.178869,0.078199,3.468665,0.106635,0.177663
32,CTSH,61.51,0,13.489035,0.105398,1.962229,0.317536,1.406461,0.254157,7.357404,0.090047,3.963508,0.14218,0.181864
33,GIS,35.585,0,8.700488,0.03856,3.436836,0.545024,1.033740,0.19715,6.532893,0.054502,3.560401,0.109005,0.188848
34,PHM,127.64,0,11.478417,0.084833,1.894387,0.28436,1.416648,0.258907,7.394241,0.094787,5.070886,0.227488,0.190075
35,DAL,73.96,0,10.797080,0.071979,2.371805,0.407583,0.745517,0.144893,7.976203,0.130332,4.781049,0.206161,0.19219
36,UNM,80.1,0,18.758781,0.246787,1.193634,0.14455,1.003149,0.190024,10.965049,0.265403,3.627304,0.116114,0.192575
37,HCA,488.1,0,17.216930,0.203085,-18.189611,0.040284,1.443783,0.266033,10.253927,0.232227,5.061924,0.225118,0.19335
38,EIX,70.255,0,6.082684,0.010283,1.582569,0.21327,1.399884,0.251781,8.623624,0.156398,6.366397,0.341232,0.194593
39,TGT,125.885,0,15.484010,0.151671,3.526487,0.554502,0.544071,0.07601,8.785349,0.168246,2.422882,0.052133,0.200512
40,PFG,95.67,0,18.222857,0.233933,1.749986,0.251185,1.327613,0.232779,11.280131,0.28673,2.823745,0.063981,0.213722
41,AIZ,228.09,0,13.464581,0.102828,1.934278,0.300948,0.886191,0.173397,7.611475,0.111374,7.370728,0.405213,0.218752
42,MAS,67.18,0,17.404146,0.210797,-74.150110,0.016588,1.808824,0.327791,11.177426,0.277251,5.857999,0.298578,0.226201
43,EMN,73.595,0,17.950000,0.226221,1.408032,0.180095,0.961561,0.180523,8.818023,0.170616,7.026713,0.386256,0.228742
44,SWK,71.845,0,27.111320,0.529563,1.230159,0.151659,0.737360,0.142518,9.890643,0.2109,3.599100,0.113744,0.229677
45,TROW,97.11,0,10.509741,0.066838,1.954395,0.312796,2.895097,0.475059,6.737820,0.066351,5.110093,0.232227,0.230654
46,DHI,151.465,0,13.782075,0.113111,1.833695,0.267773,1.315207,0.228029,10.120414,0.225118,6.109595,0.319905,0.230787
47,CLX,105.8525,0,17.324469,0.205656,-102.371860,0.011848,1.910614,0.346793,12.645730,0.36019,5.204074,0.246445,0.234186
48,BIIB,177.26,0,20.189066,0.277635,1.425321,0.184834,2.630216,0.460808,7.956916,0.127962,3.672336,0.125592,0.235366
49,PSX,155.8,N/A,14.425926,0.131105,2.148195,0.362559,0.471937,0.066508,13.050288,0.374408,5.347388,0.253555,0.237627

## Formatting Our Excel Output

We will be using the XlsxWriter library for Python to create nicely-formatted Excel files.

XlsxWriter is an excellent package and offers tons of customization. However, the tradeoff for this is that the library can seem very complicated to new users. Accordingly, this section will be fairly long because I want to do a good job of explaining how XlsxWriter works.

In [44]:
writer = pd.ExcelWriter('value_strategy.xlsx', engine='xlsxwriter')
rv_dataframe.to_excel(writer, sheet_name='Value Strategy', index = False)

## Creating the Formats We'll Need For Our .xlsx File
You'll recall from our first project that formats include colors, fonts, and also symbols like % and $. We'll need four main formats for our Excel document:

* String format for tickers
* \$XX.XX format for stock prices
* \$XX,XXX format for market capitalization
* Integer format for the number of shares to purchase
* Float formats with 1 decimal for each valuation metric

Since we already built some formats in past sections of this course, I've included them below for you. Run this code cell before proceeding.

In [45]:
background_color = '#0a0a23'
font_color = '#ffffff'

string_template = writer.book.add_format(
        {
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

dollar_template = writer.book.add_format(
        {
            'num_format':'$0.00',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

integer_template = writer.book.add_format(
        {
            'num_format':'0',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

float_template = writer.book.add_format(
        {
            'num_format':'0',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

percent_template = writer.book.add_format(
        {
            'num_format':'0.0%',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

In [46]:
column_formats = {
                    'A': ['Ticker', string_template],
                    'B': ['Price', dollar_template],
                    'C': ['Number of Shares to Buy', integer_template],
                    'D': ['Price-to-Earnings Ratio', float_template],
                    'E': ['PE Percentile', percent_template],
                    'F': ['Price-to-Book Ratio', float_template],
                    'G': ['PB Percentile',percent_template],
                    'H': ['Price-to-Sales Ratio', float_template],
                    'I': ['PS Percentile', percent_template],
                    'J': ['EV/EBITDA', float_template],
                    'K': ['EV/EBITDA Percentile', percent_template],
                    'L': ['EV/GP', float_template],
                    'M': ['EV/GP Percentile', percent_template],
                    'N': ['RV Score', percent_template]
                 }

for column in column_formats.keys():
    writer.sheets['Value Strategy'].set_column(f'{column}:{column}', 25, column_formats[column][1])
    writer.sheets['Value Strategy'].write(f'{column}1', column_formats[column][0], column_formats[column][1])

## Saving Our Excel Output
As before, saving our Excel output is very easy:

In [48]:
writer = pd.ExcelWriter('value_strategy.xlsx', engine='xlsxwriter')
rv_dataframe.to_excel(writer, sheet_name='Value Strategy', index=False)
workbook = writer.book
workbook.use_zip64()
writer.close()